### ISSUE TITLE
should mesh-name be control-plane-name?

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1140]
When we say `mesh` and `control plane`, they are really the same thing.
mesh-name is how we identify an instance of the osm control plane (what happens when you do osm install)
I'm wondering if the `mesh-name` terminology is confusing and if we should call it control plane name or id?

**Comment by shashankram** [comment]
> When we say `mesh` and `control plane`, they are really the same thing.
> mesh-name is how we identify an instance of the osm control plane (what happens when you do osm install)
> I'm wondering if the `mesh-name` terminology is confusing and if we should call it control plane name or id?

I think it would make sense to keep this as `mesh name` because:
1. OSM allows one to install multiple meshes into the cluster, and mesh is seen as a logical grouping for resources
2. In the future we could have multiple instances of the control plane running within the same mesh, so `control plane name` could be confusing

I do think the confusion could arise from lack of documentation in either case.

**Comment by shashankram** [comment]
Update:
Based on discussions, we have decided to continue to use the term `mesh name` to uniquely identify an instance of a service mesh managed by OSM control plane running within the cluster.
