### ISSUE TITLE
Consolidate cmd/cli errors into errors.go file

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#1189]
Would you mind creating an issue for the cli code? I don't have an issue with errors being defined in the file.

_Originally posted by @shashankram in https://github.com/open-service-mesh/osm/pull/1182#discussion_r459765887_

As of today the cli doesn't have a separate file with all the error messages in them like the rest of the codebase.  The main goal of this issue would be to discuss if we want consistency in the codebase , if so then a new file would be needed to have all the error messages

**Comment by shashankram** [comment]
> Would you mind creating an issue for the cli code? I don't have an issue with errors being defined in the file.
> 
> _Originally posted by @shashankram in [#1182 (comment)](https://github.com/openservicemesh/osm/pull/1182#discussion_r459765887)_
> 

I take back my original comment which resulted in this issue being created, and don't think this adds any additional value. I see this causing more inconvenience because one can't specify format specifiers in statically defined error messages as would be the case with defining errors in `errors.go`. Also considering the entire cli code is organized into a single package, don't see this being too useful.

Closing this.
