### ISSUE TITLE
Set Envoy sidecar log-level via OSM ConfigMap

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1232]
See `sidecar.go` & search the OSM repo for this issue

**Comment by knight42** [comment]
@draychev Hi! I may have missed something, could you please tell me which ConfigMap should I use?

**Comment by tapaskapadia** [comment]
I am going to try to work on this.

**Comment by shashankram** [comment]
@draychev this is a one time setting, is there value in exposing this via a command line argument to `osm-controller` vs exposing it via a ConfigMap? We only want to expose dynamic configuration via the ConfigMap. Currently there is no way to dynamically update the log level in envoy from the controller, so even if this were to be added to the config-map it wouldn't update Envoy.

**Comment by draychev** [comment]
So glad to see so much interest in this.

@shashankram -  I was thinking - we could pull the value from the ConfigMap.  Agree that this is a one-time setting for the Envoy istelf. So if you want to change that value for already running Envoys - you'd have to change the ConfigMap and do a rolling restart - the new set of Envoys would pick up this setting.

Here is where this is set:  https://github.com/openservicemesh/osm/blob/872ea6a9c1cb13e8c51555f4426c728fca18684f/pkg/injector/sidecar.go#L45
We'd have to change this in our unit tests:  https://github.com/openservicemesh/osm/blob/main/pkg/injector/config_test.go#L135
You can run tests with `make go-test`

This is the ConfigMap in question:  https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/osm-configmap.yaml

One way to quickly learn about how to get something from the `osm-config` ConfigMap to a given struct is to follow the `use_https_ingress` (https://github.com/openservicemesh/osm/search?q=use_https_ingress&unscoped_q=use_https_ingress) and then `UseHTTPSIngress` (https://github.com/openservicemesh/osm/search?q=UseHTTPSIngress&unscoped_q=UseHTTPSIngress)
Then we'd want a new interface method like this: https://github.com/openservicemesh/osm/blob/872ea6a9c1cb13e8c51555f4426c728fca18684f/pkg/configurator/methods.go#L114-L117
And then we can use this new Configurator method here: https://github.com/openservicemesh/osm/blob/872ea6a9c1cb13e8c51555f4426c728fca18684f/pkg/injector/sidecar.go#L45

@knight42 @tapaskapadia Thanks for looking into this! Happy to help if you have any questions! Assign the task to yourself if you want to take a stab at it!

**Comment by tapaskapadia** [comment]
@draychev Thanks, this PR of yours for Zipkin also helped me follow the flow. https://github.com/openservicemesh/osm/pull/1273/files 

I am going to take a stab at getting it working this weekend.

**Comment by tapaskapadia** [comment]
@draychev Would it be better practice to pass in the configurator as a parameter for the getEnvoySidecarContainerSpec function and run the method of the configurator (ex. cfg.GetEnvoyLogLevel())  inside sidecar.go or just pass in wh.configurator.GetEnvoyLogLevel() as an argument directly for getEnvoySidecarContainerSpec function in patch.go? 

Your comment above suggested the former, running the method in sidecar.go, but I wanted to make sure because SidecarImage property was handled differently and I am not certain whether or not the configurator is needed in sidecar.go. Any advice on this would appreciated. Thanks!

https://github.com/openservicemesh/osm/blob/main/pkg/injector/patch.go#L84
