### ISSUE TITLE
MacOS cannot run the osm binary

### ISSUE THREAD

**Issue by anubhavmishra** [openservicemesh/osm#1414]
**Bug description**: The osm release binary doesn't work after downloading from GitHub. This is because it might not be notarized to be used for the new macOS versions like Catalina.

**Affected area (please mark with X where applicable)**:
- [ ] Install
- [ ] SMI Traffic Access Policy
- [ ] SMI Traffic Specs Policy
- [ ] SMI Traffic Split Policy
- [ ] Permissive Traffic Policy
- [ ] Ingress
- [ ] Egress
- [ ] Envoy Control Plane
- [x] CLI Tool
- [ ] Metrics
- [ ] Certificate Management
- [ ] Sidecar Injection
- [ ] Logging
- [ ] Debugging
- [ ] Tests
- [ ] CI System

**Expected behavior**: The downloaded osm binary works for macOS.

**Steps to reproduce the bug (as precisely as possible)**: Download the osm binary from GitHub and try running in from macOS Catalina. 

**How was OSM installed?**: Using the osm CLI from GitHub. 

**Anything else we need to know?**: 

You can probably use [gon](https://github.com/mitchellh/gon) that HashiCorp wrote to notarize the OSS binary for their projects.

**Environment**:
- OSM version (use `osm version`): `Version: dev; Commit: 9e23a75; Date: 2020-08-05-15:59`
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:43:08Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15+", GitVersion:"v1.15.12-gke.2", GitCommit:"fb7add51f767aae42655d39972210dc1c5dbd4b3", GitTreeState:"clean", BuildDate:"2020-06-01T22:20:10Z", GoVersion:"go1.12.17b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
@nojnhuh would you mind trying this out on your Mac setup.

**Comment by nojnhuh** [comment]
Yes, that's correct that the binaries downloaded from the release will not run the first time they are executed because they are not notarized.

For the time being, you can workaround the issue. After running the `osm` binary the first time, you'll see a popup like this:
![image](https://user-images.githubusercontent.com/16093815/89545517-13466400-d7c9-11ea-8d4b-40cb382ab6e0.png)
Select "Cancel."

Then, open System Preferences and go to "Security & Privacy." You should see a similar dialog at the bottom of the "General" tab:
![image](https://user-images.githubusercontent.com/16093815/89545843-7932eb80-d7c9-11ea-8fa7-7c2bed4d3b8e.png)
Select "Allow Anyway."

The next time the `osm` binary is executed, another popup will be shown:
![image](https://user-images.githubusercontent.com/16093815/89546295-0d9d4e00-d7ca-11ea-8d64-4fe8fb3d3489.png)

Select "Open" and the binary will run normally.

These steps only need to be done the first time you use the CLI.

@anubhavmishra Does that help you get started? I've opened a separate issue to track notarizing the binaries: #1427

**Comment by anubhavmishra** [comment]
@nojnhuh yea, makes sense. I built the project from scratch and that worked for me.

**Comment by nojnhuh** [comment]
Excellent. I'll close this then. Thanks for pointing this out!
