### ISSUE TITLE
Document how to run maestro locally

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1710]
**Please describe what should be documented

**Please suggest where in the repo the document should be located
docs/

**Comment by nojnhuh** [comment]
I have gotten the maestro to run locally if I ensure it starts running immediately after the book* apps are deployed to mirror the behavior of CI. The problem arises for me when I start the maestro after the apps have been up and running for a while. The bookbuyer and bookthief checks consistently work, but the bookwarehouse check fails because its success token (`Restocking bookstore with 1 new books; Total so far: 3`) is only emitted once relatively soon after it starts, whereas the bookbuyer and bookthief constantly emit their success/failure tokens with every request. 

The maestro doesn't always look at the entire logs from each pod. It will look at log messages <2 seconds old and stream new logs as they come in, so the bookwarehouse's success token could be easily missed if the maestro is not started right away.

I think the simplest solution is either to make the success token a regex that matches numbers greater than 3 for the bookwarehouse or also log the regular `THIS TEST SUCCEEDED` message in the bookwarehouse whenever it receives a book past its second.

**Comment by draychev** [comment]
Maestro is being deprecated; We are using end-to-end tests and these are documented here: https://github.com/openservicemesh/osm/blob/d6d364ead3e24dac33d3c0bc42bd832a2d1d3289/tests/e2e/README.md
