### ISSUE TITLE
define and implement a set of e2e test scenarios for OSM

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1714]
This issue is to define a list of scenarious for the OSM end to end test system. These are scenarious we want to run before each PR is merged and before each release.

These scenarios should be defined in the document in the `./docs/e2e` directory.

### Sample scenarios: 
  - bookbuyer can purchase books from bookstore with an SMI policy X 
  - bookthief is not able to steal books from bookstore with SMI policy X 

### Known scenarios to test:
- [x] #1734 
- [x] #1815
- [x] #1814

**Comment by nojnhuh** [comment]
Current tests implemented in the e2e framework:
- A simple client pod can make requests to a service when allowed by a TrafficTarget.
- Same as above using Vault to issue certificates.
- 10x5 clients can make requests to 10x1 servers when explicitly allowed

Tests not yet implemented in the new e2e framework that we run in CI currently:
- Simple TrafficSplit scenario
- Egress works when enabled
- Egress does NOT work when disabled
- A simple client pod can make requests to a service when no SMI policies are present and the permissive traffic policy mode is enabled.

Other tests we should implement:
- A simple client pod cannot make requests to a service when no SMI policies are present and the permissive traffic policy mode is disabled.
- Using `helm install` instead of `osm install`

**Comment by nojnhuh** [comment]
Unlinking PR #1801 until all the outstanding e2e tests are merged.

**Comment by nojnhuh** [comment]
Now that we have a baseline set of tests in the new e2e framework, we'll open up individual issues for any future cases we want to implement.
