### ISSUE TITLE
Add check in the OSM CLI for available updates / upgrades / new versions

### ISSUE THREAD

**Issue by draychev** [openservicemesh/osm#1720]
This issue is to implement an OSM CLI command, which performs an upgrade of the control plane (and data plane if necessary) to the latest available version. For example: `osm check-update` could output `Current installed version: X;  Available new version: Y`

The design of this feature must ensure that Kubernetes clusters with older versions of the SMI CRDs continue to operate untinterrupted.

For instance: a cluster with version 1 of SMI and version 1 of OSM is upgraded to version 2 of OSM.  Version 2 of OSM must continue to work with version 1 of SMI.

Unanswered questions:
 - how many legacy SMI CRD versions is the latest OSM control plane going to support?

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**

**Comment by draychev** [comment]
ref https://github.com/openservicemesh/osm/issues/893 https://github.com/openservicemesh/osm/issues/512 https://github.com/openservicemesh/osm/issues/1603

**Comment by ksubrmnn** [comment]
[OSM CRD Upgrade doc](https://docs.google.com/document/d/1PreYEK-geTonBmPiMAbztzs9zXV8rs15pt1Y-t82uQE/edit?usp=sharing)

**Comment by nojnhuh** [comment]
For a first pass at this command, I envision a thin wrapper over `helm upgrade` with a subset of the flags available on `osm install` to tweak the chart values. This could handle simple updates like only modifying fields in the `osm-config` ConfigMap or more significant updates like changing the `osm-controller` image to a newer version that would require a control plane restart. Since Helm only modifies the resources that change between releases, changes only to the ConfigMap will not restart the control plane, for example.

Since all the parameters available to a user to change are in the chart's values.yaml, having a single CLI command that leverages `helm upgrade` for any control plane configuration changes seems to be the simplest to use and understand vs. segmenting parameters under different CLI commands.

### Examples

Modify the ConfigMap, osm-controller not restarted:
```console
$ osm mesh update MESH_NAME --enable-egress
```

Upgrade the control plane image versions, osm-controller restarted:
```console
$ osm mesh update MESH_NAME --osm-image-tag=v0.6.1
```

Modify both the ConfigMap and osm-controller deployment, osm-controller restarted:
```console
$ osm mesh update MESH_NAME --osm-image-tag=v0.6.1 --enable-egress
```

---

Any concerns or other ways we can improve this approach?

/cc @michelleN

**Comment by johnsonshi** [comment]
GA requirement

**Comment by snehachhabria** [comment]
@johnsonshi I see that you are assigned to this issue, please could you share the status of this? If you are no longer working on the please could you unassign yourself

**Comment by johnsonshi** [comment]
Resolved through https://github.com/openservicemesh/osm/pull/4416
