### ISSUE TITLE
install watch as part of demo run

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#1785]
**Please describe the Improvement and/or Feature Request**
On a new machine that didn't have `watch` installed and needed it to run the demo. Would be great to install this as part of the demo or a script to install requisites or as part of a make target.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [X ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
As a user, I want to run the demo as smoothly as possible.

**Comment by nojnhuh** [comment]
Installing packages is one of those things that is both very distro-specific and personal preference that I'd be afraid to maintain a script here to do it automatically. Since it's already documented as a pre-req, the most I would want to do here ideally would be point to the pre-req docs if it's not installed. If it's critical to have installed beforehand, I would suggest we download a static binary to `bin/` and invoke that if it's not already installed. I'm not sure that's worth the hassle though for what it does.

Perhaps an additional `echo "The demo is up and running!"` or some other confirmation message right before the watch is called would help clarify that even if the watch fails, the rest of the script still worked.

**Comment by shashankram** [comment]
This seems unnecessary to include as a part of the demo run. I agree with what @nojnhuh mentioned in https://github.com/openservicemesh/osm/issues/1785#issuecomment-707975728.

Since this is clearly mentioned as a prerequisite in the demo guide https://github.com/openservicemesh/osm/blob/main/demo/README.md#system-requirements, I am closing this one. 

Feel free to reopen if you disagree.
