### ISSUE TITLE
make book demo applications in one namesapce

### ISSUE THREAD

**Issue by hysyeah** [openservicemesh/osm#1811]
I have run osm demo and found that osm create one namespace for each application,like that bookbuyer,bookstore,bookief,bookwarehouse.
I think deploy the demo in one namespace can make it more simplicity and more suitable for the use of namespace.

**Comment by hysyeah** [comment]
\assign

**Comment by hysyeah** [comment]
I think i can try to resolve it. someone can assign it to me ?

**Comment by shashankram** [comment]
The reason the demo uses multiple namespaces is because there are scenarios we want to showcase communication between traffic in different namespaces.

That being said, the app namespaces are driven via environment variables, so by default we could set the app namespaces to be the same: https://github.com/openservicemesh/osm/blob/main/demo/run-osm-demo.sh#L20-L23
