### ISSUE TITLE
OSM CLI and Chart version compatibility

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2293]
**Please describe what should be documented

Document the following when the OSM CLI and the installed Chart version are different:
- expected experience
- known issues
- workarounds 

**Please suggest where in the repo the document should be located
https://github.com/openservicemesh/osm/blob/main/docs/installation_guide.md

**Comment by nojnhuh** [comment]
Reiterating what I mentioned offline to help keep track:

> Since the osm cli embeds a specific version of the chart, is there any compatibility issues or requirements if a user uses version of the osm cli with a diff version of the chart? 

> Yes, there's nothing I know of in the CLI that handles other chart versions. For example, if a value name is changed in the chart, then its corresponding `osm install` flag (if one exists) will not work for an older CLI version. Issues with the values could be worked around today by using `osm install --set` to set arbitrary overrides. Other issues may certainly exist, but the install flags -> values mapping issue is the main one I see.

**Comment by shashankram** [comment]
Is it possible we allow users to override the chart version to use through the cli, as a way of dynamically loading a newer chart that is compatible with an older cli binary?

**Comment by bridgetkromhout** [comment]
> Is it possible we allow users to override the chart version to use through the cli, as a way of dynamically loading a newer chart that is compatible with an older cli binary?

Is this issue expanding to include this idea? I think this would require new code.

**Comment by shashankram** [comment]
> > Is it possible we allow users to override the chart version to use through the cli, as a way of dynamically loading a newer chart that is compatible with an older cli binary?
> 
> Is this issue expanding to include this idea? I think this would require new code.

There are 2 parts to it:
1. Document clearly in the docs website what the compatibility is for the CLI and docs
1. Make code changes to achieve 1

**Comment by bridgetkromhout** [comment]
I will leave this issue in place to cover the code changes needed, and I will make a related issue for the docs changes.

**Comment by nojnhuh** [comment]
Offline we decided that we are only going to support the CLI when working with the chart with the same version, e.g. v0.9.2 of the CLI will only support v0.9.2 of the chart. Many operations will likely continue working when there is some version skew between the CLI and chart, but that's not something we will commit to supporting for now.

Upgrades are a special case since that inherently deals with multiple chart versions. Each CLI version will support upgrading from the versions as described [here](https://github.com/openservicemesh/osm-docs/blob/795ae620f989a283cbe85e5f94796ff8a483969f/content/docs/getting_started/upgrade.md#policy) only to the version of the chart that matches its version. For example, some v0.10.2 of the CLI would support upgrading the chart from version v0.10.0 or v0.10.1 to only v0.10.2.

To be clear, this isn't a change in what's currently supported, but I'm not sure this is explicitly documented. I'll work on openservicemesh/osm-docs#94 for the docs changes.

**Comment by nojnhuh** [comment]
Docs changes have been merged in https://github.com/openservicemesh/osm-docs/pull/180
