### ISSUE TITLE
Extend support for host headers with configuring routes

### ISSUE THREAD

**Issue by ksubrmnn** [openservicemesh/osm#2369]
SMI Traffic Spec allows us to specify headers and Host is one of these.

We use the kubernetes host names when building the envoy configs. This means we disregard any host header specified in the traffic spec ( for both a traffic target and traffic split)

We need to extend out the route configuration to provide support for it

**Comment by shashankram** [comment]
Can this be addressed with the routes refactor?
/cc @michelleN

**Comment by snehachhabria** [comment]
@shashankram yes it will be, @ksubrmnn will be handling it while working on this : https://github.com/openservicemesh/osm/issues/2368

**Comment by snehachhabria** [comment]
As of today we are ignoring host headers : https://github.com/openservicemesh/osm/blob/b25fd46fefa3a8dd7bbbbc350bb966eef803d37a/pkg/envoy/route/config.go#L152 

We will have to ensure that it's included in the headers and domains while configuring routes. Since we want this support, changing it from documentation to enhancement required

**Comment by draychev** [comment]
Let's push this to v0.9  or 0.8.1  cc: @phillipgibson @michelleN

**Comment by michelleN** [comment]
sounds good. added to #2611

**Comment by snehachhabria** [comment]
Once we support configuring routes with headers, users will still not be able to make requests to the hosts. As there's limitation in OSM  to only supports service fqdn's on its filter chains.

**Comment by snehachhabria** [comment]
This issue is blocked on this : https://github.com/openservicemesh/osm/issues/3150

**Comment by shashankram** [comment]
I wanted to call out that specifying a custom host header in SMI's traffic specs doesn't serve any purpose at the moment. Per the current implementation, a host header derived from an SMI HTTPRouteGroup resource is programmed as a header match in a route's match criteria (`route.match.headers[]`).

Such a route needs to first match the `virtual_host.domains` in the route configuration, where matching is already performed based on the HTTP `:authority` (same as `Host`) header. With the existing implementation, a route with a header match based on the host header derived from an SMI HTTPRouteGroup resource will be programmed, though it will never be used because traffic with that host header will not match the top-level `virtual_host` the route belongs to.

The only use case to specify a host header match in an envoy route is when using a wildcard (`*`) `virtual_host`, to be able to differentiate routes with different host headers part of the wildcard `virtual_host`.
