### ISSUE TITLE
Add e2e scenarios for routes v2 feature flag enabled

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2391]

**Comment by snehachhabria** [comment]
Routes v2 would impact the following scenarios for e2e : 

- [X] 1. e2e_permissive
- [X] 2. e2e_deployment_client_server
- [ ] 3. e2e_trafficsplit
- [ ] 4. e2e_trafficsplit_same_sa
 
With PR #2501 (1) and (2) have been addressed

**Comment by shashankram** [comment]
We have 2 tests for routesV2 currently:
permissive mode: https://github.com/openservicemesh/osm/blob/main/tests/e2e/e2e_routesv2_permissive_test.go
smi: https://github.com/openservicemesh/osm/blob/main/tests/e2e/e2e_routesv2_smi_traffic_target_test.go

Since routesV2 will become the default and is expected to work with the existing suite of e2e tests, we do not need additional tests specifically for routesV2 at the moment.
