### ISSUE TITLE
Provide more information when OSM install fails

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#2508]
**Please describe the Improvement and/or Feature Request**
Provide more information when install fails with the `osm install` command.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Project Release            [ ]

**Possible use cases**
There is not enough information presented with `osm install` command fails. This becomes problematic especially with the atomic flag set while installing the Helm charts, because the install namespace is cleaned up and there is not an easy way to know the reason for the failure. 
Consider the following error message which does not provide meaningful information regarding the failure:
```
Error: release osm failed, and has been uninstalled due to atomic being set: timed out waiting for the condition
```

**Comment by nojnhuh** [comment]
I'm not aware of a way to hook into Helm to make it do something like print the status of all the resources it installs before it uninstalls the release. I think the simplest change would be to use the equivalent of `--wait` instead of `--atomic`, then if the install fails, the CLI does some inspection, prints results, then cleans up the release itself.

One current workaround would be to set `osm install --timeout` to some really long time so you have time to debug before the resources get cleaned up. That assumes you have access to the cluster though, so wouldn't be helpful for e2e tests running in kind.

Related to #1530

**Comment by shashankram** [comment]
I think it will be beneficial to get as much information as possible when installation fails, else users are going to raise tickets without enough information available, which is going to significantly slow triage times.

Following options come to mind:
1. Remove atomic flag and let user run `helm uninstall` to cleanup stale resources
2. Make the Helm atomic flag configurable 
3. Remove atomic flag and use a post install hook to handle log collection and resource deletion on install failure 

As you have suggested, I have been using the `--timeout` flag as a workaround to debug install failures where I need a window to inspect the testbed quickly. But in general we need a way to collect enough information for offline debugging when the install fails, without requiring access to a live environment.
