### ISSUE TITLE
move development guide outside of website content

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2724]
The OSM development guide is repo specific and might make more sense being under docs/ rather than under docs/content which is content for the docs website. Currently lives docs/content/docs/dev_guide/_index.md.

**Comment by shashankram** [comment]
@michelleN I would prefer development guide be rendered on the website as well, just because the guide will have links to other documentation within the repo which would make it easier to navigate if contained within the website. I don't see any downside to having the development guide rendered on the website.

**Comment by bridgetkromhout** [comment]
related: https://github.com/openservicemesh/osm/blob/main/DESIGN.md appears to be largely similar content to https://github.com/openservicemesh/osm/tree/main/docs/content/docs/design_concepts - do we plan to continue updating it in two places? That seems like it will get out of sync.

**Comment by michelleN** [comment]
It should be in one place or the other @bridgetkromhout. Makes more sense to be on the website.

Closing this issue as there have been no strong opinions to move the dev guide outside of the website and it is still accessible within the repo.
