### ISSUE TITLE
Revisit release process

### ISSUE THREAD

**Issue by ritazh** [openservicemesh/osm#2841]
Should pre-releases be created from main?
- When cutting a new pre-release, that commit should land in main first, then cherry pick to release-* branch.

Con:
- One concern is stability of main as new rc releases land, it may not be stable yet.

**Comment by nojnhuh** [comment]
> Should release branch be created from main?

Release branches are created from main, unless I'm misunderstanding what you mean by this. v0.8.0-rc.1 was the current `main` + one commit to update hardcoded versions. v0.8.0-rc.2 was v0.8.0-rc.1 + select patches from `main` since v0.8.0-rc.1 + one commit to update hardcoded versions.

> * When cutting a new release, that commit should land in main first, then create release-* branch from main and all commits thereafter would land in main first, then cherry pick to release-* branch.

What current problem is this trying to address exactly?

When we cut a new non-pre-release, we do update main to reference the new version after all the the release is published. I don't see a big difference in making the updates in `main` right before vs. right after cutting the release.

https://github.com/openservicemesh/osm/blob/8004e656c611dababe4492453ee70ea9c73d2bc1/docs/content/docs/release_guide.md#L86-L90

**Comment by ritazh** [comment]
> Release branches are created from main

ok good.

> What current problem is this trying to address exactly?

https://github.com/openservicemesh/osm/pull/2822 updates the image tags in release branch but not in main. image tags in main are now older than the those in release branch, which caused this issue #2840
Ideally we want main to have the most up to date information. 

> When we cut a new non-pre-release, we do update main to reference the new version after all the the release is published

I see so I guess this issue is just specific to pre-releases then?

**Comment by allenlsy** [comment]
https://github.com/openservicemesh/osm/pull/3533
