### ISSUE TITLE
move osm metrics enable/disable to osm namespace command

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2942]
Should the metrics enable/disable functionality be flags on the osm namespace command rather than their own parent command? You can enable/disable metrics on a namespace, so it is related to namespace management.

cc/ @eduser25

**Comment by shashankram** [comment]
@michelleN it was done this way for the following reasons:
1. Because it made sense to have all metrics related commands consolidated under the `osm metrics` subcommand
2. Because there were also inquiries to enable metrics on a per pod basis

To support 2, if we moved metrics under the namespace command we would need to create another command just for pods, ex. `osm pod enable-metrics --pod <name>`?

I think it might make sense for metrics to be its own subcommand just because this will very likely be extended in the future to expose other metrics-related functionality. 

Something like `osm namsepace enable-metrics foo` also looks okay, just that my preference would be to house all metrics related CLI commands under `osm metrics ...`

**Comment by michelleN** [comment]
gotchya the per pod metrics scenario seems like a good justification for keeping it in a separate command. thankss
