### ISSUE TITLE
Move osm webhook configuration resource ownership from Helm to OSM Controller

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2961]
**Please describe the Improvement and/or Feature Request**
Mutating and validating webhooks should be created by osm-controller. Similar to and depends on https://github.com/openservicemesh/osm/issues/2932. See #2932 for more details.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Comment by ritazh** [comment]
Both `ValidatingWebhookConfiguration` and `MutatingWebhookConfiguration` have lots of options/knobs users would want to configure, e.g `namespaceSelector`, `failurePolicy`. If osm controller owns the lifecycle management of these resources, then it needs to expose all these options for users to configure and those values will need to be persisted during an upgrade. There is also the risk of feature drift as osm controller will need to keep up with updates introduced in these kinds in upstream.

**Comment by shashankram** [comment]
I think it would be beneficial to have the webhook managed entirely for the following reasons:

1. Creating the webhook config resources via Helm and patching it within the controller/injector are prone to race conditions and depend on the order in which these resources (webhook configuration, control plane deployments) get deployed. Currently we are at the mercy of Helm to order resources the way it deems fit. This is pretty fragile because some resources are deployed in alphabetical order: https://github.com/helm/helm/blob/master/pkg/releaseutil/kind_sorter.go
2. As @ritazh mentioned, the configurable knobs on the webhook configurations might need to be exposed within the controller, which complicates the code. Exposing these directly in charts allows users to easily override them via Helm's `set` flag.
3. The TLS certificate used by the webhooks does not need to be provisioned by OSM's own certificate provider. If the webhook configurations are completely maintained by Helm, the user could use certificates of their choice to authenticate the webhook cert with the K8s API server. It is not impossible to populate the webhooks's `caBundle` attribute in the Helm chart, rather a bit more complicated than one would by using Go code. Moreover, these certificates do not need to be rotated similar to Envoy workload certificates (by OSM).
4. If the webhook configurations are completely maintained in Helm, the user could choose to reconcile the resources the way they want, using their own tools without having to deal with race conditions that would arise if the controller were to patch it.
5. It would simplify the upgrade workflow, where changing the chart would be enough to upgrade the webhook config. Moving it into the control plane app would mean one would need to upgrade the controller. This means one could upgrade just the webhook configuration without needing to disrupt the control plane.

For these reasons, my personal preference would be to have the webhook configurations be entirely managed by Helm.

**Comment by snehachhabria** [comment]
After a few offline discussions we had decided not to move the webhook ownership into the osm controller. We will let this resource be managed by Helm only and will work on upgrading it leveraging helm itself.
