### ISSUE TITLE
osm namespace list lists ignored namespaces incorrectly

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#2965]
To replicate: 
```console
$ osm namespace add bookbuyer
# deploy an app in bookbuyer namespace. done for you by automated demo.

$ osm namespace list 
NAMESPACE       MESH   SIDECAR-INJECTION
bookbuyer       osm    enabled

$ osm namespace ignore bookbuyer
Successfully configured namespace [bookbuyer] to be ignored

$ osm namespace list 
NAMESPACE       MESH   SIDECAR-INJECTION
bookbuyer       osm    enabled

```

After `osm namespace add` and deploying an app in bookbuyer ns, the bookbuyer pod has 2 containers running in it as expected. After `osm namespace ignore` and deleting the bookbuyer pod, the bookbuyer pod gets recreated with 1 container in it as expected. The problem is with `osm namespace list` which shows that bookbuyer is still a namespace in the mesh with sidecar injection labeled because the label and annotation for namespace monitoring still exist on the ns. `osm namespace list` doesn't take into account which namespaces have the ignore label on them when it should. 

As part of the work to solve this issue:
1. Update `osm namespace list` with an `ignored` column
2. Should the `osm namespace ignore` command remove the monitored by label and sidecar injection annotation from the namespace metadata?
3. Verify any other situations where the osm codebase should be ignoring the namespace but may not be because it is not evaluating the ignore label.
4. Document `osm namespace add` + `osm namespace ignore` behavior in the namespace_monitoring.md file. https://github.com/openservicemesh/osm/pull/2941#discussion_r597874476

**Comment by nojnhuh** [comment]
> 1. Update `osm namespace list` with an `ignored` column

Since the `ignore` label only has to do with sidecar injection, would it make more sense to override the `SIDECAR-INJECTION` column to `disabled` if the `ignore` label is set? Or maybe a bit more explicitly like `disabled (ignored)`? I worry that "ignored" with no other qualifier wouldn't make complete sense in this context.

> 2. Should the `osm namespace ignore` command remove the monitored by label and sidecar injection annotation from the namespace metadata?

Doing too much label swizzling in the CLI won't prevent this same thing from happening when `kubectl` is used directly to label the namespace, so I think it would be best for the CLI to handle any combination of labels/annotations.
