### ISSUE TITLE
Allow inbound access from non-mesh clients

### ISSUE THREAD

**Issue by addozhang** [openservicemesh/osm#2986]
**Please describe the Improvement and/or Feature Request**

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [x]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

During our architecture migration poc, we are facing this case. The service provider is in mesh now, but consumer not yet.

If a default filter chain arranged to inboud lister too, will solve this issue. The provider will serve the traffic from consumer diectly, not through consumer's sidecar.

**Comment by shashankram** [comment]
@addozhang Currently, inbound traffic is only accepted if one of the following is true:
1. The service is accepting traffic from in-mesh clients
2. The service has an ingress resource

It seems like you are requesting the addition of a default_filter_chain on the inbound listener so that the service can accept traffic from clients that are not a part of the mesh but within the cluster.

This is currently not supported. We will need to think through how to make this (non-mesh client -> in-mesh service) work without breaking existing workflows.

**Comment by addozhang** [comment]
@shashankram yes, please. I think it will be helpful in mixed architect and help service migration smoothly. 😀

**Comment by shashankram** [comment]
> @shashankram yes, please. I think it will be helpful in mixed architect and help service migration smoothly. 😀

I understand the use case. I was wondering if setting the cluster to use `permissive_traffic_policy_mode` will help you, which is meant for exactly this purpose. Currently permissive_traffic_policy_mode relies on clients to be also part of the mesh, but there is a simple fix to allow it to accept traffic from clients outside the mesh.

@addozhang Would it be possible for you to share some sample k8s deployments to replicate this with OSM? What kind of service are you using (HTTP, TCP, gRPC, Redis, mySQL etc.)?

**Comment by addozhang** [comment]
Currently we have service communicating via http, and also have some middleware such as redis, Kafka, MySQL which are TCP.

We are going to push service decveloper to migrate to mesh by providing "Canary Release" feather (we have other reason why we can not provide it in our Java SDK). You know they won't move without anything attractive. If with permissive_traffic_policy_mode, the splits will not be involved in route construction. (I remember we discussed why we can not enable permissive_traffic_policy_mode before.)

With envoy 1.17.x providing default filter chain, it's really helpful to proxy request to service which is not in mesh but in cluster.

Our system is built on SpringCloud (service discovery is Eureka) and Openshit 3.11 (kubernetes 1.11). Both of them are in ancient version.

With mesh, we hope to decouple business logic with SpringCloud by sinking feature to sidecar.

If you require some deployment sample, I can provide some. I think they are similar with demo applications provided by osm. The difference is service discovery is Eureka and service communicating with pod IP and port directly.

What I have done now is extended spring cloud feign to convert Eureka instance to Kubernetes one (service.namespace:port). With this change,we don't much change in osm.

Now with 0.8.0 code, we did changes below:
- provide noop ingress client to mock method bcoz Openshit we are using has Router instead of Ingress (mentioned in another issue)
- disable mTLS relative code
- set default filter chain to inbound listener like you did for outbound. (not enable passive)
- fix PodIPs empty by reading IP from Pod IP field
- set resource limitations for init and envoy containers (mentioned in another issue too)
- self hosted charts bcoz the ancient still has v1beta CustomerResourceDedinition and some changes in mutatingadmissionhook.

I know I asked for many requirements, but they are useful in smooth migration.

**Comment by shashankram** [comment]
> Our system is built on SpringCloud (service discovery is Eureka) and Openshit 3.11 (kubernetes 1.11). Both of them are in ancient version.
> 

OSM does not support k8s versions <= 1.15. Since 1.11 is deprecated, we do not support this version. OSM currently only tests versions >= 1.17 <= 1.20.2.

As of this moment, there is no plan to support deprecated k8s versions, or versions as old as k8s 1.11.

> Now with 0.8.0 code, we did changes below:
> 
> * provide noop ingress client to mock method bcoz Openshit we are using has Router instead of Ingress (mentioned in another issue)
> * disable mTLS relative code
> * set default filter chain to inbound listener like you did for outbound. (not enable passive)
> * fix PodIPs empty by reading IP from Pod IP field
> * set resource limitations for init and envoy containers (mentioned in another issue too)
> * self hosted charts bcoz the ancient still has v1beta CustomerResourceDedinition and some changes in mutatingadmissionhook.
> 
> I know I asked for many requirements, but they are useful in smooth migration.

I understand why you need this change, just that it needs to be thought through and evaluated to not interfere with existing feature support in OSM. For example, just adding a default_filter_chain on the inbound listener will break SMI + permissive mode because a service will not start accepting traffic from non-mesh clients when it is not supposed to. This means if we add a default_filter_chain for the inbound listener, we need to make this configurable etc.

**Comment by Fodoj** [comment]
What about Ingress controllers that are not part of the cluster, like the ones for cloud load balancers? For example, AWS Load Balancer Ingress controller creates an AWS ALB, which is a thing that is not inside the cluster, but routes traffic to the cluster. Right now with permissive mode connections are still timing out - seems like exactly because ALB is not part of the mesh.

**Comment by shashankram** [comment]
> What about Ingress controllers that are not part of the cluster, like the ones for cloud load balancers? For example, AWS Load Balancer Ingress controller creates an AWS ALB, which is a thing that is not inside the cluster, but routes traffic to the cluster. Right now with permissive mode connections are still timing out - seems like exactly because ALB is not part of the mesh.

Ingress is orthogonal to permissive mode. Kindly refer to https://main--osm-docs.netlify.app/docs/guides/traffic_management/ingress/ to allow access from an ingress controller (in-cluster or out-of-cluster) to an app within the mesh. More specifically, you want to be using the `IPRange` kind to allow traffic from the external LB: https://main--osm-docs.netlify.app/docs/guides/traffic_management/ingress/#examples
