### ISSUE TITLE
Pubsub does not guarantee subscription is committed and active upon sub return

### ISSUE THREAD

**Issue by eduser25** [openservicemesh/osm#3144]
There might be a race on Pubsub library creation and use, where Pubsub
could have potentially not finished subscribing due to the nature
of Go, and we might miss an event as a consequence in some corner cases.

Subscribing uses unbuffered channel message passing to subscribe internally,
inside pubsub lib. A goroutine handles the actual subscription (adding the sub channel to maps, etc).
Depending on scheduling, a quick publish on a channel recently subscribed to
could theoretically loose the event if the scheduler didn't fully finish the subscribe
handler (ie. the routine yielded for whatever reason).

ex:
```
subChannel := pubsub.sub(topic)
emitEvent(topic)
<-subChannel
```
Registration of pubsub happens asynchronously, and just ensures that the routine handling registration did receive the event through unbuffered channel communication:
https://github.com/cskr/pubsub/blob/master/pubsub.go#L68
however, this does not guarantee that the subscription is fully committed and active. The routine handling registration could still yield upon internal function call.

We normally don't care as many of our packages do not work on heavy sub/unsub operations (subscriptions happen regularly at package init and the channel stays for its lifetime), but this could very well affect tests that quickly initialize and expect value propagation in a subscription in very tight code.

**Bug description**:

- Envoy Control Plane        [X]

**Expected behavior**:
Subscription call return should ensure subscription is up and running.

**Comment by shashankram** [comment]
@eduser25 It seems like we may need to implement reliable event delivery within osm-controller to get around this.

**Comment by eduser25** [comment]
pretty much. We could consider to implement write-back communication in the library itself, doesn't look too hard.
naively, something like:
```
func (ps *PubSub) sub(op operation, topics ...string) chan interface{} {
	ch := make(chan interface{}, ps.capacity)
	ps.cmdChan <- cmd{op: op, topics: topics, ch: ch}
	return ch
}```
to:
```
func (ps *PubSub) sub(op operation, topics ...string) chan interface{} {
	ch := make(chan interface{}, ps.capacity)
        done := make(chan struct{})
	ps.cmdChan <- cmd{op: op, topics: topics, ch: ch, done: done}
	<-done  
	return ch
}
```
I'll take a look at their github.

**Comment by shashankram** [comment]
Since the pubsub pkg handles both pub and sub within a single goroutine for the duration of the pub-sub instance, it is important for subscribers to be provisioned before events are published in tests. If a subscriber is not registered, the published message will be a no-op for the subscribed topics.

The pub-sub does not have to guarantee that a subscription is committed by the time `Sub()` returns, because it simply returns a channel on which the subscriber receives published messages. Publishers cannot be blocked on subscribers being ready, because there can be more than one subscriber for a topic.

In tests that require guarantees, there is a wait period after a subscription that gives enough time for the subscription to be committed by the pub-sub instance. Practically, I have not seen a need to address this outside of tests. 

I am closing this as there is nothing actionable at the moment.
