### ISSUE TITLE
Retain original configurability in values.yaml

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#3301]
**Bug description**:

This PR : https://github.com/openservicemesh/osm/pull/3276 resulted in some fields being deleted from the values.yaml. This change would break customers and isn't undesirable, we would like to add the fields that were deleted.

Part of #2738 

**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by allenlsy** [comment]
Pull request is created at #3307 .

However, I think there is a flaw in the initial solution design. Using only `preset-mesh-config` can take the arguments from `osm install`, but it does not work with `osm upgrade`. Because in the design, once `osm-mesh-config` exists, init container will ignore `preset-mesh-config`. Arguments passed into `osm upgrade` will not take effect.

If we want `osm upgrade` to work with arguments, here is my proposal.

* MeshConfig template in Helm charts should allow customizable resource name.
* `osm install` will set the resource name to `preset-mesh-config`. If init container sees `preset-mesh-config`, it will create a `osm-mesh-config` from preset if `osm-mesh-config` does not exist.
* `osm upgrade` will set the resource name to `upgrade-mesh-config`. It will use the CLI arguments to overwrite values in values.yaml. If init container sees `upgrade-mesh-config`, it will update values in existing `osm-mesh-config`.

**Comment by draychev** [comment]
I wonder about this:
> If we want osm upgrade to work with arguments

Why would we want `osm upgrade` with arguments?  What arguments are these? Would these be arguments that change the config on top of upgrading the mesh?

**Comment by snehachhabria** [comment]
This is a part of #3039
