### ISSUE TITLE
extend bookstore sample application to write to a database

### ISSUE THREAD

**Issue by michelleN** [openservicemesh/osm#3328]

**Comment by draychev** [comment]
The bookwarehouse could record

**Comment by allenlsy** [comment]
1. Do we care what type of database? Redis or MySQL?
2. Do we deploy the database as a separate k8s service, or a sidecar of bookstore?

**Comment by michelleN** [comment]
1. No we don't care what type of database
2. Separate Kubernetes service to model a closer to real world scenario

**Comment by shashankram** [comment]
> 1. Let's use Redis since the dapr demo Sneha did uses Redis and we've had a few end users play with the Redis in their apps
> 2. Separate Kubernetes service to model a closer to real world scenario where we have apps we may want to upgrade that talk to a database running as a separate instance

I suggest not using Redis in the demo for a few reasons:
1. Redis protocol uses TCP as the transport and doesn't behave any differently than regular TCP traffic, for which we have enough coverage.
2. Redis uses terminology that is insensitive to many. While they have made an effort to provide alternatives, we don't want to be offending anyone, and using Redis in our demo opens the door for unnecessary distractions that none of us want to deal with.
3. We can get additional coverage by including mySQL or PostgreSQL since these are `server-first` protocols, and OSM has additional logic to support server-first protocols. In server-first protocols, the server initiates the first byte of data after a connection handshake.
