### ISSUE TITLE
retries: Read annotations from TrafficTarget SMI policy

### ISSUE THREAD

**Issue by shalier** [openservicemesh/osm#3339]
This GitHub issue is a sub-component of #3338. The goal is to create a POC of implementing retry between 2 services in a service mesh.

This GitHub issue is for the exploration of how SMI policies may be augmented to declare Retry Policy (provide metadata).

### Proposal
We can define the annotations for retry policy on the TrafficTarget policy. This issue is to determine a way to access these annotations.
See [doc](https://docs.google.com/document/d/19OdsrHARJ87AXdeaU0075Z4PSRrn-RPhMYRZEwcPO3g/edit#) for additional info.

**Comment by shashankram** [comment]
FWIW, we need to first agree that these annotations should go on a TrafficTarget resource. Retry policies are applicable to services, so I believe this should go on a service resource, to begin with.

**Comment by draychev** [comment]
> FWIW, we need to first agree that these annotations should go on a TrafficTarget resource. Retry policies are applicable to services, so I believe this should go on a service resource, to begin with.

@shashankram Thanks for challenging the assumptions here. 

Here is what @shalier and I discussed today.
We need a retry policy to be declared between some source client X and a destination service Y.
If we were to implement the retry in the source client, we'd do it as some loop, counter, sleep(), some max value etc.
The outcome of our discussion was - the policy is applied not on a particular vertex - neither X, nor Y, but on the directed edge X-Y.
![image](https://user-images.githubusercontent.com/49918230/118193492-a6699580-b3fc-11eb-9cbb-d7370b82aae8.png)

If applied the policy on the source client X -- it would be unclear what the destination is. X may be connecting to Y and Z.
It is quite likely that you want to declare a retry policy on X connecting to Y but **not** when X connects to Z.
To illustrate this: 
![image](https://user-images.githubusercontent.com/49918230/118193924-60f99800-b3fd-11eb-9d1e-0a782fc6c909.png)

For the same reason - it does not seem right to put these annotations on the destination Kubernetes Service either.

So looking for an object than represents the **edge** between two vertices (X and Y) - we have TrafficTarget. 
TrafficTarget to me seems like the link between 2 payloads (the edge). This is where the proposal comes from to add annotations to the TrafficTarget.

> Note: This is all a POC. This is mainly to explore and learn. Annotations seem like a really light weight way to do this. Eventually we should also mature this into what an actual SMI augmentation may look like.

**Comment by shashankram** [comment]
@draychev Thanks for the explanation. Would you mind sharing a design doc for review once you have an implementation proposal in mind. How would retries work in permissive mode (if that's a design goal)?

For a POC, an annotation will suffice.

**Comment by allenlsy** [comment]
Sharing my thoughts here:

On the client-server communication edge, the retry policy (includes max time of retries, retry interval etc.) should be declared by the server side. Because server has the knowledge about how much load it can handle, and the logic of supporting retries. Client side should do best effort to follow the policy. 

Thus, I think ideally retry policy needs to be added to TrafficTarget scheme. This is also a common feature that service mesh should support. In production use cases, service owner of the server-side will manage the TrafficTarget objects.

But I don't think we should create a separate RetryPolicy CRD. On the communication edge, there are other aspects that we may support users to customize, such as load balancing algorithm, rate limiting policy etc. It will be inconvenient to manage if we create CRD for each aspect. Adding them to TrafficTarget with default settings can be a good starting point.

For this issue, since TrafficTarget does not support retry policy for now, using annotation sounds good.

**Comment by shashankram** [comment]
> Sharing my thoughts here:
> 
> On the client-server communication edge, the retry policy (includes max time of retries, retry interval etc.) should be declared by the server side. Because server has the knowledge about how much load it can handle, and the logic of supporting retries. Client side should do best effort to follow the policy.
> 
> Thus, I think ideally retry policy needs to be added to TrafficTarget scheme. This is also a common feature that service mesh should support. In production use cases, service owner of the server-side will manage the TrafficTarget objects.
> 
> But I don't think we should create a separate RetryPolicy CRD. On the communication edge, there are other aspects that we may support users to customize, such as load balancing algorithm, rate limiting policy etc. It will be inconvenient to manage if we create CRD for each aspect. Adding them to TrafficTarget with default settings can be a good starting point.
> 
> For this issue, since TrafficTarget does not support retry policy for now, using annotation sounds good.

I disagree that using TrafficTarget is the correct approach. In my opinion, it would be a hack to do so, because TrafficTarget is based on ServiceAccount. Retries should be scoped to a service. It is common for pods to be deployed in an environment with the same service account, but this doesn't imply all the services backed by those pods need to use the same retry policy. Moreover, different service protocols (HTTP, TCP, gRPC etc.) will require different retry semantics. Using annotations here will be hacky and inflexible.

Take a look at how other meshes implement retries:
https://istio.io/latest/docs/concepts/traffic-management/#retries
https://kuma.io/docs/1.1.2/policies/retry/#usage
