### ISSUE TITLE
Broken link in ingress documentation

### ISSUE THREAD

**Issue by mudit-01** [openservicemesh/osm#3346]
For ingress configuration from this link (https://github.com/openservicemesh/osm/blob/e3b7afe081e39373aa4b339e1805dcf0b288653b/docs/content/docs/tasks_usage/traffic_management/ingress.md#other-ingress-configurations) it mentions Demos for using OSM with other Ingress resources available at this(https://github.com/openservicemesh/osm/tree/main/docs/content/docs/tasks_usage/traffic_management/demos) but this link is NA

**Comment by shashankram** [comment]
@mudit-01 OSM uses docs.openservicemesh.io as its source of truth for documentation that is available on the website. Due to the complexity and differences between how links are navigable on the website and github, it is not feasible for content to be seamlessly navigable both on the website and github. For this reason, please refer to docs.openservicemesh.io and not github for user-facing documentation.

The link https://docs.openservicemesh.io/docs/tasks_usage/traffic_management/demos/ works fine on the website and is navigable from the ingress page https://docs.openservicemesh.io/docs/tasks_usage/traffic_management/ingress/ correctly.
