### ISSUE TITLE
Investigate the use of self runners for OSM's CI

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#3716]
We are facing capacity issues with the current GH runners and will have to explore using self hosted runners for our CI  

https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners#supported-architectures-and-operating-systems-for-self-hosted-runners

**Comment by draychev** [comment]
To show where this is (because it took me a second to find it):

![image](https://user-images.githubusercontent.com/49918230/124189115-15ff1700-da75-11eb-9f4c-b9d99178b08f.png)

---

![image](https://user-images.githubusercontent.com/49918230/124189147-2616f680-da75-11eb-9dba-f6c3a58b4bae.png)

---

![image](https://user-images.githubusercontent.com/49918230/124189269-5068b400-da75-11eb-8d1c-537eb09979da.png)

**Comment by snehachhabria** [comment]
We have temporarily solved this problem by increasing the nodes on the cluster running the CI with this PR : https://github.com/openservicemesh/osm/pull/3813

**Comment by snehachhabria** [comment]
Closing this issue for now since the CI is running as expected with increased nodes
