### ISSUE TITLE
osm_request_duration_ms referenced in docs, but doesn't exist in osm code

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#3728]
**Bug description**: osm_request_duration_ms referenced in docs, but doesn't exist in osm code. Only `osm_request_duration_ms_bucket`, `osm_request_duration_ms_sum`, `osm_request_duration_ms_count` exist, however they aren't referenced in docs. Additionally, summing duration and counting duration does not make sense as a metric.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [X]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:
* Install osm with prometheus. Run the osm bookstore demo in the background.
* Initiate prometheus port forward using demo directory's port forward script.
* Go to localhost prometheus endpoint.
* Use `osm_request_duration_ms` but it won't work.
* Use metrics like `osm_request_duration_ms_bucket`, `osm_request_duration_ms_sum`, `osm_request_duration_ms_count` and it would work.

**How was OSM installed?**: `osm install --set=OpenServiceMesh.deployPrometheus=true`

**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`): `v0.9.1`
- Kubernetes version (use `kubectl version`): `v1.19.11`
- Size of cluster (number of worker nodes in the cluster): 2
- Others:

**Comment by nojnhuh** [comment]
The metric is registered with the name `osm_request_duration_ms`:
https://github.com/openservicemesh/osm/blob/0641d7289eb97a45ba9c13e340899557f44115cd/wasm/stats.cc#L30

Because it's a histogram (as mentioned in the [docs](https://github.com/openservicemesh/osm-docs/blob/85a61c3590ba2311b3224047f8fed1ee7328d161/content/docs/tasks/observability/metrics.md#L177)), Prometheus derives the bucket/sum/count metrics that would be queried directly: https://prometheus.io/docs/concepts/metric_types/#histogram

> Additionally, summing duration and counting duration does not make sense as a metric.

I haven't used the sum/count metrics, so what I'm about to say might be totally wrong, but I think they do make sense even if the names may not be intuitive. Based on that same link to the Prometheus docs, the count is the number of requests between two endpoints and the sum would be the total time taken in aggregate for all requests between them. So you could do something like `sum / count` to get the average request duration.

Overall, the most I would suggest to change is the addition of the actual metric names (bucket/sum/count) to the docs. I get that it's not super clear how you would get to those names otherwise if you're not familiar with Prometheus histograms, but I'm not sure this doc alone will ever be free of points of confusion like this for people with little to no prior knowledge of Prometheus.

**Comment by shashankram** [comment]
@johnsonshi could you update the docs as per the suggestion in https://github.com/openservicemesh/osm/issues/3728#issuecomment-874986625

**Comment by shashankram** [comment]
> @johnsonshi could you update the docs as per the suggestion in [#3728 (comment)](https://github.com/openservicemesh/osm/issues/3728#issuecomment-874986625)

@johnsonshi kindly follow-up on the doc changes required. From the update above, it seems like the product is behaving as expected, so closing this.
