### ISSUE TITLE
Implement SMI Metrics

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#379]
this will help extending the k8s API for users to make metrics requests (for resource defined in SMI spec)

- [x] [Extend Envoy to get custom metrics around source of traffic](https://github.com/open-service-mesh/osm/issues/984) 
  - [x] #998 
  - [x] #1013
- [ ] [Implement SMI metrics api server](https://github.com/openservicemesh/osm/issues/1540)

**Comment by jshaughn** [comment]
Hi @michelleN . does this open issue mean that OSM does not yet make request metrics available for consumption?

**Comment by michelleN** [comment]
@jshaughn - OSM does make available metrics around success/error rate and latency available and you can view them already via the `osm dashboard` command. The [SMI metrics spec](https://github.com/servicemeshinterface/smi-spec/blob/master/apis/traffic-metrics/traffic-metrics-WD.md) requires us to compute some more granular metrics between a source and destination (for example between a two specific Pods or Deployments) so that is what is being done with this work.

**Comment by jshaughn** [comment]
@michelleN Thanks for the response.  Pod-specific metrics are less interesting given the more dynamic nature of pods but the traffic for more logical aggregations of pods, like Deployments, is what I was looking for.

**Comment by snehachhabria** [comment]
closing this issue as we have an implementation of smi metrics already.
