### ISSUE TITLE
Windows based demo containers

### ISSUE THREAD

**Issue by davinci26** [openservicemesh/osm#3880]
All the containers in `dockerfiles` should have a Windows equivalent and we should expand the makefile to build them

**Comment by davinci26** [comment]
As I was working in https://github.com/openservicemesh/osm/pull/3921

I realized that we are running into a fundamental issue with how I was planning on building Windows containers from the CI.

I discussed internally with the team that produces the insider version of containers (https://hub.docker.com/_/microsoft-windows-nanoserver-insider/) and I found out that these containers can be used with `docker buildx`.

This means that for the time being we have two options for building the Windows demo containers:

1. Add a Windows host in the CI and build the demo containers from there. The obvious downside is that these involves maintenance and it will need to be deprecated in a couple of months when Windows Server 2022 is GA.
2. Manually push the images and have no automation at this point. When Windows Server 2022 is GA we should be able to add #3921 as it is.

**Comment by davinci26** [comment]
@michelleN @draychev wdyt?

**Comment by ksubrmnn** [comment]
How often would images need to be pushed?

**Comment by ksubrmnn** [comment]
Where would the Windows host be located?

**Comment by davinci26** [comment]
> How often would images need to be pushed?

Not sure, hopefully not that many times but we might need to iterate 1-2 times as we work through the demo and the tests.

> Where would the Windows host be located?

It will be a VM on Azure.

**Comment by nojnhuh** [comment]
> 2. Manually push the images and have no automation at this point. When Windows Server 2022 is GA we should be able to add [feat(windows): [Do not merge] Adds demo containers based on Windows #3921](https://github.com/openservicemesh/osm/pull/3921) as it is.

I think the demo images change infrequently enough that this would be fine as a stop-gap for a few weeks. However, since the CI assumes the control plane and demo images use the same tag which changes for every commit, we'd either have to completely decouple those or manually re-tag and push the demo images manually and somehow synchronize that during CI runs, which doesn't seem feasible to me. Decoupling the control plane and demo image tags doesn't sound too bad, but would involve a pretty wide set of changes that I highly doubt we'd get right the first time.

Overall, my hunch is adding a Windows machine to the CI seems like it would be the easier and less disruptive option. How much upkeep would we expect to need for that VM over the next few weeks?

**Comment by ksubrmnn** [comment]
Depending on the time estimate, I like option 1. +1 to Jon's point

**Comment by davinci26** [comment]
Sorry got confused by what Windows Host means in this case. I thought you meant for the k8 cluster but it is probably in the context of the CI.

The windows host should be available on AzureDevops as a managed option. i.e. we do not need to maintain it

**Comment by davinci26** [comment]
See https://github.com/actions/virtual-environments#available-environments

**Comment by davinci26** [comment]
Awesome, option 1 it is, I will work on adding a Windows based job on the CI that will only build the demo containers.

**Comment by ksubrmnn** [comment]
> Sorry got confused by what Windows Host means in this case. I thought you meant for the k8 cluster but it is probably in the context of the CI.
> 
> The windows host should be available on AzureDevops as a managed option. i.e. we do not need to maintain it

Yep, meant in the context of the CI. Are you able to build the insider images from Windows Server 2019?

**Comment by davinci26** [comment]
> Are you able to build the insider images from Windows Server 2019?
I haven't tested it but I think it should be possible with hyper-v isolation mode

**Comment by davinci26** [comment]
@ksubrmnn was right and it is not possible to build these images from Windows Server 2019.

With this info I think that manually pushing the container images and building them locally is the best way forward now. I think it might be too much work to self-host a build agent for a couple of months. WDYT?

**Comment by ksubrmnn** [comment]
Sounds good to me. There aren't a ton of examples of using insider builds for these purposes. Waiting until GA for automation seems very reasonable

**Comment by ksubrmnn** [comment]
Could you please write some short documentation about this process? 

1. We could just keep it in the repo instead of osm-docs since it's still in development. 
2. You could write docs in osm-docs but explicitly state that the project is in development and not GA/ready for customer testing.

I prefer option 1 since I don't think it's feasible for customers to try this out themselves just yet, but it would be good to have dev docs so others can try building these images themselves.

@nojnhuh what do you think?

**Comment by nojnhuh** [comment]
Yeah, keeping docs in the osm repo makes the most sense to me.

**Comment by ksubrmnn** [comment]
I recommend making a windows directory in https://github.com/openservicemesh/osm/tree/main/docs
