### ISSUE TITLE
Grafana Dashboard: Decrement not working

### ISSUE THREAD

**Issue by nshankar13** [openservicemesh/osm#3918]
**Bug description**: After a namespace, pod, or service is deleted from the mesh, the corresponding counter in the Grafana dashboard is not being decremented. 

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [X]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**: Install OSM, create a namespace and add it to the mesh, then deploy a pod/service in that namespace. Open Grafana dashboard, then try deleting the namespace/pod/service`

**How was OSM installed?**: OSM CLI from main with Grafana and Prometheus enabled. 

`./bin/osm install             --set=OpenServiceMesh.image.registry="$CTR_REGISTRY"             --set=OpenServiceMesh.image
.tag="$CTR_TAG" --set=OpenServiceMesh.deployPrometheus=true --set=OpenServiceMesh.deployGrafana=true`
**Anything else we need to know?**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by eduser25** [comment]
Not sure if related, but https://github.com/openservicemesh/osm/issues/2604 can affect. If the monitored namespace is no longer monitored, deletes on that namespace can be not taken into account.

**Comment by jaellio** [comment]
Related stack overflow [post](https://stackoverflow.com/questions/68671062/prometheus-promql-query-is-not-showing-0-when-metric-data-does-not-exists?newreg=73b8a204879a4be29477090dea6c94c4).

**Comment by jaellio** [comment]
This is not an issue with Grafana. The values for the K8sAPIEventCounter metrics are correct. The PromQL query incorrectly calculates the number of resources of a certain type. The existing query is as follows:

`sum(osm_k8s_api_event_count{type="namespace-added", source_pod_name=~"$osm_controller_instance"}) by (source_pod_name) OR on() vector(0) - sum(osm_k8s_api_event_count{type="namespace-deleted", source_pod_name=~"$osm_controller_instance"}) by (source_pod_name) OR on() vector(0)`

Separately, `sum(osm_k8s_api_event_count{type="namespace-added", source_pod_name=~"$osm_controller_instance"}) by (source_pod_name)` and `sum(osm_k8s_api_event_count{type="namespace-deleted", source_pod_name=~"$osm_controller_instance"}) by (source_pod_name)` will report the correct count. When these counts are subtracted from each other the resulting value is incorrect. This may be because of the behavior of prometheus counters with labels.

If the K8sAPIEventCounter metric hasn't been incremented with the type label set as `namespace-added` the query `osm_k8s_api_event_count{type="namespace-added", source_pod_name=~"$osm_controller_instance"}` will return no data. Prior to being incremented, the metric with that specific label combination has no value. The queries above attempt to solve this by adding `OR on() vector(0)`. If the sum returns no data then the zero vector is used instead. However, the query still returns the incorrect value in the scenario described by nshankar13.

This query also does not take into account when a namespace is no longer being monitored. The resources in that namespace should not be included in the resource counts for the mesh.  

Ultimately, the query incorrectly handles when there is no data and does not account for resources that have been removed from the mesh.

**Comment by jaellio** [comment]
- [ ] Remove inaccurate values from the Grafana dashboard (values calculated using the k8sapieventcounter)
- [ ] Add Namespace count metric for monitored namespaces
- [ ] Update `Monitored Namespaces` pane to use the NamespaceCount metric
