### ISSUE TITLE
Request failure due to envoy wasm_fail_stream

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#3958]
**Bug description**:
Requests from `bookbuyer/bookbuyer` -> `bookstore/bookstore` fails due to `wasm_fail_stream` error.:

Request:
```
Fetching http://bookstore.bookstore.svc.cluster.local:14001/buy-a-book/new
Request Headers: map[]
Error fetching http://bookstore.bookstore.svc.cluster.local:14001/buy-a-book/new: Get "http://bookstore.bookstore.svc.cluster.local:14001/buy-a-book/new": EOF
ERROR: response code for "http://bookstore.bookstore.svc.cluster.local:14001/buy-a-book/new" is 0;  expected 200
```

Envoy log:
```
{"response_code":0,"protocol":"HTTP/1.1","upstream_service_time":null,"bytes_received":0,"method":"GET","requested_server_name":null,"start_time":"2021-08-12T16:57:15.032Z","response_code_details":"wasm_fail_stream","authority":"bookstore.bookstore.svc.cluster.local:14001","time_to_first_byte":null,"upstream_host":null,"x_forwarded_for":null,"upstream_cluster":"bookstore/bookstore","path":"/buy-a-book/new","user_agent":"Go-http-client/1.1","duration":0,"bytes_sent":0,"request_id":"dc4bd3af-5643-423e-bc8b-64d201fde953","response_flags":"-"}
```

**Affected area (please mark with X where applicable)**:
- Envoy Control Plane        [X]

**Expected behavior**:
Requests should not fail.

**Steps to reproduce the bug (as precisely as possible)**:
Contact @trstringer for repro.

**How was OSM installed?**:
@trstringer to comment

**Bug report archive**:

[278997373_osm-bug-report.tar.gz](https://github.com/openservicemesh/osm/files/6977262/278997373_osm-bug-report.tar.gz)

**Environment**:
- OSM version (use `osm version`): `v0.9.1`

- Kubernetes version (use `kubectl version`):
```
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.19", GitCommit:"ac0cc736d0018d817c763083945e4db863168d12", GitTreeState:"clean", BuildDate:"2021-05-13T17:13:35Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by trstringer** [comment]
Steps to reproduce:

1. Create aks-engine cluster with a single control plane node
2. Install OSM from commit SHA a25e3ead0a6cce8aab0b83911696ba49453e6fda
3. Install the bookstore application from the same commit
4. Reboot the control plan node
5. Observe the intermittent failures between bookbuyer and the bookstore

It did take a couple of hours for that behavior to appear in my situation. Some of the requests from bookbuyer to bookstore succeeded with http/200, but some failed with the `wasm_fail_stream` error above.

**Comment by nojnhuh** [comment]
Trying to repro, ~40 minutes after master reboot things are looking normal to me: 
![image](https://user-images.githubusercontent.com/16093815/129267661-6cfc669d-2ec5-4500-b6ed-efc1065f0265.png)

"wasm_fail_stream" not found in the bookbuyer or bookstore-v1 logs yet either.

Googling shows nothing but three results that are all Envoy source code. The only references I found are here, but I can't really gather how Envoy would get to this point: https://github.com/envoyproxy/envoy/blob/98c1c9e9a40804b93b074badad1cdf284b47d58b/source/extensions/common/wasm/context.cc#L1587-L1619

Has this happened more than on this one cluster?

**Comment by trstringer** [comment]
@nojnhuh I still have the original cluster up, but I'll try to get an additional repro to validate my repro steps.

**Comment by nojnhuh** [comment]
I'm seeing it happen now: 
![image](https://user-images.githubusercontent.com/16093815/129272620-1edd64b7-1e5e-4337-8a7f-01ace61e2542.png)

And I'm seeing the `wasm_fail_stream` errors in the bookbuyer logs.

**Comment by nojnhuh** [comment]
I think I have a solution, but still not sure exactly what the root cause is here.

Since this smells like a memory leak somewhere, I checked out the Envoy container memory usage in Prometheus. I noticed it would slowly creep up from about 45M on startup to about 60M on the bookbuyer before the requests start failing.

I tried taking out or changing various parts of wasm/stats.cc to see if that affected this behavior.  After a few iterations of that the culprit seemed to be the `Counter` and `Histogram` from proxy-wasm. I don't see any requests failing even after several hours when those aren't used at all. Since we need those for the stats to work, I tried moving the `Counter` and `Histogram` from the per-stream `Context` object to the persistent `RootContext`. With that change, the same metrics are still recorded and requests have been succeeding for me for over 16 hours so far with Envoy container memory usage staying constant.

Overall I'm not sure if we can say this is a memory leak in proxy-wasm or Envoy or if I just didn't have the metrics set up correctly in the WASM.
