### ISSUE TITLE
Make RetryPolicy a generic API so it works with both SMI and permissive mode

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#4038]
**Please describe the Improvement and/or Feature Request**
The current implementation of RetryPolicy in OSM relies on annotations applied to the TrafficTarget resource. This however does not work in permissive mode since TrafficTarget objects are not leveraged.

Leverage a generic API to implement retry policy such that there is no dependency on SMI TrafficTarget to configure retries.

**Scope (please mark with X where applicable)**
- New Functionality          [X]

**Comment by allenlsy** [comment]
There were discussions about this issue here: 

https://github.com/openservicemesh/osm/issues?q=is%3Aopen+is%3Aissue+retry+label%3Aarea%2Fretries

I prefer the solution of a OSM specific CRD for retry policies. We need to a design doc for the feature, since it can easily involve:

* supported protocols: HTTP / TCP / gRPC?
* Granularity of the policy: per destination SA? per HTTP path? 
* Configurable fields: interval / max retries?

cc @shalier

**Comment by shashankram** [comment]
Duplicate of https://github.com/openservicemesh/osm/pull/4476
