### ISSUE TITLE
Update Grafana dashboards in Grafana UI 

### ISSUE THREAD

**Issue by snehachhabria** [openservicemesh/osm#4282]
**Please describe the Improvement and/or Feature Request**

OSM Grafana charts rare imported to Grafana UI as well here : https://grafana.com/grafana/dashboards/14145. The dashboards here are very old and have not been updated for a long time. Please update them with the dashboards from : https://github.com/openservicemesh/osm/tree/release-v0.11/charts/osm/grafana/dashboards .

Once this done, pdate the documentation here as needed : https://github.com/openservicemesh/osm-docs/blob/327c06c3ca1fc73d421bd785841e278903942044/content/docs/demos/prometheus_grafana.md#importing-osm-dashboards

We should also add this to the release process, whereby every time a new release is cut the dashboards in the Grafana UI are also updated.  Please update the release documents based on the steps followed to update s that anyone doin the release is aware and follows the required steps. 

- [x] #4525

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [X]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
Upto date dashboards in Grafana UI

**Comment by snehachhabria** [comment]
@jaellio would you be able to take this up, since you have experience with Grafana ?

**Comment by jaellio** [comment]
@phillipgibson filed a support request with Grafana labs to unblock this issue.

**Comment by jaellio** [comment]
With @shalier's help, I created this [PR](https://github.com/openservicemesh/osm-docs/pull/280) in the OSM docs repo to **temporarily** remove references to Grafana.com in the instructions for getting the OSM Grafana dashboards. Once the support request with Grafana Labs has been resolved references to Grafana.com can be added back to the docs. 

The Grafana images on the docs site are updated in this [PR](https://github.com/openservicemesh/osm-docs/pull/284) and reflect the dashboards in v1.0.0-rc.2. 

With the above-mentioned PRs, this issue is no longer a blocker for v1. I think this issue should be moved to the vNext milestone.
