### ISSUE TITLE
Helm Chart should accommodate custom image names

### ISSUE THREAD

**Issue by ron1** [openservicemesh/osm#4331]
**Please describe the Improvement and/or Feature Request**

The OSM Helm Chart should accommodate the use of custom image names.

**Scope (please mark with X where applicable)**
- New Functionality          [ ]
- Install                    [X ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**

The OSM Helm Chart should accommodate the use of custom image names. For example, some users may want to mirror the OSM images similar to how Rancher currently mirrors Istio images here: https://github.com/rancher/rancher/releases/download/v2.6.2/rancher-images.txt. A relevant extract from the rancher-images.txt file is included below. The current Helm Chart prevents the use of an image prefix like "mirrored-" in this example.
```
rancher/mirrored-istio-citadel:1.5.9
rancher/mirrored-istio-coredns-plugin:0.2-istio-1.1
rancher/mirrored-istio-galley:1.5.9
rancher/mirrored-istio-install-cni:1.10.4
rancher/mirrored-istio-kubectl:1.5.9
rancher/mirrored-istio-mixer:1.5.9
rancher/mirrored-istio-node-agent-k8s:1.5.9
rancher/mirrored-istio-pilot:1.10.4
rancher/mirrored-istio-pilot:1.5.9
rancher/mirrored-istio-proxyv2:1.10.4
rancher/mirrored-istio-proxyv2:1.5.9
rancher/mirrored-istio-sidecar_injector:1.5.9
```

**Comment by nojnhuh** [comment]
Some initial thoughts on this:

- I don't think we should make any assumptions about the format of the image references provided by users, so we should have users fully specify each image separately. I think it should be perfectly valid to use images from different registries or with different tags, e.g.
  - I can see however this may make it painful for developers who want to use images built from source vs. only specifying a registry and tag, but I think it would be relatively simple to make shortcuts for this in the demo scripts.
- w.r.t. upgrades, removing the way we currently define images (`osm.image.{registry,tag,digest}`) would be a breaking change according to Helm where Helm would expect a major version bump of the chart version. `helm upgrade` users will run into issues if they expect `--reuse-values` to work for a chart whose major version isn't bumped and we redo these values. For `osm mesh upgrade`, I don't think this will matter as much since only the values for old chart are totally ignored unless a user manually specifies them with `--set`.
