### ISSUE TITLE
Upgrading OSM does not upgrade default values in the MeshConfig

### ISSUE THREAD

**Issue by trstringer** [openservicemesh/osm#4371]
**Bug description**:

When you upgrade OSM, if there are changes that need to be in the MeshConfig (e.g. sidecar image) then these do not take effect after the upgrade.

**Affected area (please mark with X where applicable)**:
- Install                    [x]

**Expected behavior**:

Certain configurations in MeshConfig should be upgradeable as well, as long as they were not altered by the user.

**Steps to reproduce the bug (as precisely as possible)**:

Install OSM version v0.9.2:

```bash
$ osm version
Version: v0.9.2; Commit: 7df9badece2f251515a2bc5e5ac79438b0c58812; Date: 2021-08-19-21:02

$ osm install
OSM installed successfully in namespace [osm-system] with mesh name [osm]
```

Notice the settings for the sidecar image (this is expected for v0.9.2):

```bash
$ kubectl get meshconfig -n osm-system osm-mesh-config -o jsonpath='{.spec.sidecar.envoyImage}'
envoyproxy/envoy-alpine:v1.18.3
```

Now upgrade OSM (both the CLI and the cluster components) to v1.0.0-rc.2:

```bash
$ osm version
Version: v1.0.0-rc.2; Commit: bee1cac865a33360f1669d139969636c5ee6fd2f; Date: 2021-11-15-17:21
~
 $ osm mesh upgrade
OSM successfully upgraded mesh [osm] in namespace [osm-system]
~
 $ kubectl logs -n osm-system osm-controller-9db65477b-wz7rd | head -n 1
{"level":"info","component":"osm-controller/main","time":"2021-11-18T15:47:37Z","file":"osm-controller.go:124","message":"Starting osm-controller v1.0.0-rc.2; 7351ad3173ddd7595447c49371f5d056ce1b4cc9; 2021-11-12-16:10"}
```

And see that the MeshConfig has not changed (not desired) for the sidecar image:

```bash
$ kubectl get meshconfig -n osm-system osm-mesh-config -o jsonpath='{.spec.sidecar.envoyImage}'
envoyproxy/envoy-alpine:v1.18.3
```

Just to prove that an installation (not an upgrade) of v1.0.0-rc.2 does not have this same setting, start with a new cluster and install OSM v1.0.0-rc.2:

```bash
$ osm version
Version: v1.0.0-rc.2; Commit: bee1cac865a33360f1669d139969636c5ee6fd2f; Date: 2021-11-15-17:21
~
 $ osm install
OSM installed successfully in namespace [osm-system] with mesh name [osm]
~
 $ kubectl get meshconfig -n osm-system osm-mesh-config -o jsonpath='{.spec.sidecar.envoyImage}'
envoyproxy/envoy-alpine@sha256:6502a637c6c5fba4d03d0672d878d12da4bcc7a0d0fb3f1d506982dde0039abd
```

A base installation of v1.0.0-rc.2 has the correct MeshConfig value for the sidecar image.

**How was OSM installed?**:

```bash
$ osm install
```

**Anything else we need to know?**:

Looking at [the comment for `osm mesh upgrade`](https://github.com/openservicemesh/osm/blob/5229967b5c8dbb193f006cd1bd81d57d11367afd/cmd/cli/mesh_upgrade.go#L32-L36):

> Note: edits made to chart values that impact the preset-mesh-config will not
apply to the osm-mesh-config, when "osm mesh upgrade" is run. This means configuration
changes made to the osm-mesh-config resource will persist through an upgrade
and any configuration changes needed can be done by patching this resource prior or
post an upgrade.

It appears as though this behavior is currently expected.

I think that the correct behavior is to "upgrade" MeshConfig values that have been unchanged. Effectively that would mean that any options that the user has kept as default should remain as default for the current version of OSM.

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by nshankar13** [comment]
Thanks @trstringer for creating this issue. 

I was able to reproduce this from upgrading from v0.9.2 to v1.0.0-rc.2. The specific error that's happening with envoy after is that the envoy bootstrap is expecting the "connect_timeout" field in osm_controller, which I think is a field required for envoy v1.18.3 but not v1.19.1. But because envoy v1.18.3 is still being injected into the service pods with v1.0.0-rc.2 of the osm-controller, the configuration fails. 

For instance, when I try creating the bookbuyer deployment in the mesh, I see the following error in the envoy container of the bookbuyer pod: 

`[2021-11-18 22:50:05.503][1][critical][main] [source/server/server.cc:113] error initializing configuration '/etc/envoy/bootstrap.yaml': Field 'connect_timeout' is missing in: name: "osm-controller"` 

It seems like to avoid these kinds of errors in future upgrades, we either need to ensure backwards compatibility or edit specific fields in the meshconfig like sidecarImage upon upgrades.
