### ISSUE TITLE
osm-bootstrap's debug server should be disabled to save perf - it does not return meaningful data as of now

### ISSUE THREAD

**Issue by johnsonshi** [openservicemesh/osm#4450]
**Bug description**:

Should metrics server be disabled on osm-bootstrap to save perf? The osm-bootstrap metrics endpoint doesn’t return anything useful. See screenshot below on the scarce osm-bootstrap metrics data, showing that bootstrap debug server should be disabled.

**Affected area (please mark with X where applicable)**:
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:

**Steps to reproduce the bug (as precisely as possible)**:

**How was OSM installed?**:

![image](https://user-images.githubusercontent.com/13926417/149388568-c31560df-9b72-449a-b489-9efc6e97a402.png)

**Anything else we need to know?**:

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`):
- Kubernetes version (use `kubectl version`):
- Size of cluster (number of worker nodes in the cluster):
- Others:

**Comment by shashankram** [comment]
@johnsonshi I am reading the term `debug server` and this is confusing in this context, as I believe you are referring to the metrics endpoint. The term `debug server` is primarily used in the context of osm-controller which exposes a debug endpoint (different from metrics). All applications should ideally expose a metrics server for debugging purposes. Even osm-bootstrap does not publish meaningful metrics at this moment, in the future we will for certain add more metrics to be able to root cause issues just from looking at some of the process metrics. There are also not any perf implications to consider here without concrete data.

For the reason stated above, I think it makes sense to keep the metrics server on osm-bootstrap as is.
