### ISSUE TITLE
CRD reconciler handles the same updates twice

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#4575]
**Bug description**:

While adding metrics to the reconciler as a part of #4568 I noticed the metric increasing by one after deleting a CRD but by two each time I update a CRD. These are the changes I've made to add the metrics: https://github.com/nojnhuh/osm/commit/e724c77f0fd966c63429dbe6be98176efd410d0c

After adding some more logs it looks like the second update is the same as the first, not the change made by the reconciler. I wonder if this has to do with the client-go docs saying [not to modify resources](https://pkg.go.dev/k8s.io/client-go/tools/cache#ResourceEventHandler) received by informers' event handlers, which happens here: https://github.com/openservicemesh/osm/blob/c522ed19cccabfa0b93ae5f5accacf6993bba81a/pkg/reconciler/crd_handler.go#L38-L40

I tried working around modifying the objects from the cache but found more unexpected behavior described below.

**Expected behavior**: The reconciler runs exactly once each time it sees a resource is deleted or updated.

**Steps to reproduce the bug (as precisely as possible)**:
With the changes I linked above from my fork checked out:
```
make kind-up
demo/run-osm-demo.sh --set osm.enableReconciler=true
kubectl port-forward -n osm-system deploy/osm-bootstrap 9091
curl localhost:9091/metrics   # => osm_reconciliation_total not listed (0)
kubectl delete crd ingressbackends.policy.openservicemesh.io
curl localhost:9091/metrics   # => osm_reconciliation_total{kind="CustomResourceDefinition"} 1
kubectl patch crd ingressbackends.policy.openservicemesh.io -p '{"spec": {"names": {"shortNames": ["jon"]}}}'
curl localhost:9091/metrics   # => osm_reconciliation_total{kind="CustomResourceDefinition"} 3
```

**How was OSM installed?**: Auto demo

**Anything else we need to know?**:
The overall behavior of the CRD reconciler otherwise looks fine, i.e. after deleting a CRD it reappears and after updating a CRD it's changed back.

In order to not modify the cached objects sent to the informer handlers, I tried to `.DeepCopy()` them here but that brought other issues: https://github.com/openservicemesh/osm/blob/c522ed19cccabfa0b93ae5f5accacf6993bba81a/pkg/reconciler/crd_handler.go#L20-L21

Running the demo with that additional change shows the same behavior when deleting the CRD, the metric inscreases by one and the CRD is recreated. Then when the same CRD is updated, the metric increases by only one but the change doesn't take effect because `apierrors.IsConflict(err)` is true on the error from the reconciler's update. Then I restart the osm-bootstrap deployment to trigger its init container to reset the CRD. Next I update the CRD manually to trigger and reconcile and the reconciler spirals where the changes it makes start triggering additional reconciliations, so it's in an endless loop of updating the CRD. Deleting the CRD stops the loop, but subsequent updates to the CRD are the same as before, where the update done by the reconciler fails so manual changes persist.

Overall I'm not sure why we don't see this same endless reconciliation happening already since I don't see where the reconciler would be ignoring changes made by itself.

**Environment**:
- OSM version (use `osm version`): Same commit as linked above
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4", GitCommit:"e6c093d87ea4cbb530a7b2ae91e54c0842d8308a", GitTreeState:"clean", BuildDate:"2022-02-16T12:30:48Z", GoVersion:"go1.17.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster): three nodes, kind
- Others:

**Comment by nojnhuh** [comment]
I don't remember being a part of those early discussions, so I don't know. It looks like https://github.com/openservicemesh/osm/issues/1909 is the earliest reference I can find for reconciling resources like this in general and https://github.com/openservicemesh/osm/issues/4065 specifically for CRDs. @shashankram may be able to help.

**Comment by shashankram** [comment]
> @nojnhuh can you provide context on why we use a reconciler vs validating/mutating webhooks?

I don't understand the comparison being drawn here as the reconciler was introduced for a very targeted use case - to reconcile the CABundle field (among a few other fields) in k8s resources (webhooks, CRDs) to its original value if it was accidentally changed by a user who has permission to change them. This was also a requirement from some customers running OSM in a managed environment, where they wanted the functionality to ensure certain fields are always reconciled to their original value.

**Comment by shashankram** [comment]
> > > @nojnhuh can you provide context on why we use a reconciler vs validating/mutating webhooks?
> > 
> > 
> > I don't understand the comparison being drawn here as the reconciler was introduced for a very targeted use case - to reconcile the CABundle field (among a few other fields) in k8s resources (webhooks, CRDs) to its original value if it was accidentally changed by a user who has permission to change them. This was also a requirement from some customers running OSM in a managed environment, where they wanted the functionality to ensure certain fields are always reconciled to their original value.
> 
> Thanks for the context! cabundle is different, but for the CRD’s is there any reason not to use a validating and mutating we hook?
> 
> that is, can you describe a use case the reconsider solves that the former doesn’t? Thanks!

The reconciler is a generic framework meant to reconcile any undesirable changes to the CRD and control plane webhooks to their original state, only as long as the reconciler is enabled. It does not prevent users from making changes or removing them, which may be required in some cases during maintenance or migrations, or during the uninstall of the software. So the idea behind using a reconciler is to allow the control plane to mutate it however it deems correct, the correctness of which is determined at runtime (not defined statically similar to the code executed by the validating webhook to validate allowed values on API resources). 

That said, it is possible to use a validating webhook to validate CRUDs on a CRD. However, the removal of the CRD during an uninstall/upgrade gets more complicated as the validating webhook configuration also would need to be tweaked to allow updates to them. As you can imagine, this requires dealing with timing issues to coordinate desired updates to the CRD when the validating webhook config is present on the cluster. With the reconciler, as long as the process has terminated, no such additional synchronization is necessary to perform a cleanup/update of the CRD. 
Further, since the reconciler also reconciles the validatingwebhookconfiguration resource, I am unsure if there can be a validatingwebhookconfiguration to validate another validatingwebhookconfiguration resource. Even if it were possible, I can imagine it causing various circular dependency issues that might not work reliably.

The use of the reconciler in OSM primarily addresses very specific use cases (CABundle correctness on k8s resources, CRD correctness). If we can simplify this further, sure we can evaluate potential alternatives.

**Comment by nojnhuh** [comment]
Closing since I'm no longer seeing this issue consistently. I occasionally see it the first time I `kubectl patch` a CRD, but never after that, so I think this may just be a side effect of how the API handles things that we can't control.
