### ISSUE TITLE
standalone prometheus data source and grafana dashboard installation?

### ISSUE THREAD

**Issue by aakash-rajur** [openservicemesh/osm#4598]
**Bug description**:
- the provided helm chart seems to install prometheus deployment with prometheus scrape config mandatorily
- the provided helm chart seems to install grafana deployment with grafana dashboards mandatorily
- the chart seem to be inflexible to situations where both prometheus and grafana are pre-installed in cluster
- no option to add or remove any of the prometheus data source or grafana dashboard
- prometheus and grafana stack have their respective operator use case as well
- don't seem to understand the reason why these components (specifically the deployments) are included in the first place?

**Affected area (please mark with X where applicable)**:
- Install                    [X]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [ ]
- CLI Tool                   [ ]
- Metrics                    [X]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- Demo                       [ ]
- CI System                  [ ]

**Expected behavior**:
mechanism to install prometheus scrape config and grafana dashboards separately
https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/prometheus-configmap.yaml#L1
https://github.com/openservicemesh/osm/blob/main/charts/osm/templates/grafana-configmap.yaml#L1

**How was OSM installed?**:
helm chart

willing to contribute, awesome project. thank you for the effort

**Comment by trstringer** [comment]
Thank you for opening this issue! The approach that we've taken with Prometheus and Grafana out of the box with OSM is a very generic but common usage of these tools. Instead of having additional controls to customize these experiences, another possibility is to install, configure, and manage Prometheus and Grafana away from OSM.

This would give you the desired level of control and as a power user of these tools this is likely what you're looking for.

Let me know if this helps.
