### ISSUE TITLE
Implement support for setting 'status' fields on custom resources

### ISSUE THREAD

**Issue by shashankram** [openservicemesh/osm#4619]
**Please describe the Improvement and/or Feature Request**

Some custom resources such as `IngressBackend` and `UpstreamTrafficSetting` have a `status` field that can be set. Currently, `UpdateStatus()` API in the `k8s.Controller` interface can be used to update the status of the object. However, this is not a robust solution for the following reasons:
1. The object read from the cache whose status is being updated can be outdated by a more recent write in a different goroutine. This will result in the status update to fail.
2. It is possible for multiple control plane instances to concurrently update the status on a resource, which will result in conflicts.

Implement a generic status management framework to handle status updates on objects in a graceful manner while dealing with conflict resolution.

**Scope (please mark with X where applicable)**
- Control Plane        [ ]

**Possible use cases**
Status reporting for custom resources.

**Comment by steeling** [comment]
1. I don't think we should implement 1 off support for retries specifically on status updates. There are other things we can/should update throughout the code as well, where retries may be useful, and this should be part of a general reconciler.
2. Since this is simply a need to retry a failed write, level-triggered reconciliation would be the recommended fix.
3. We currently have level based reconciliation implemented in ticker.go, although @shashankram has mentioned there are some performance concerns in using that. I'd be interested to see what those are and if it makes sense to fix those vs rolling a new level-based reconciler. My guess is there's some low hanging fruit in simply setting a minTickInterval to prevent a tight loop there.
4. We may need places in the code that check if the status needs to be updated. ie: Check if the status is already set appropriately, and don't update it if so.
5. Probably change error logs due to optimistic concurrency control to warnings.

**Comment by steeling** [comment]
I also think we should try to come up with a concrete repro before attempting any specific fix

**Comment by keithmattix** [comment]
I agree with @steeling's last point; without a repro, this is all theoretical. If we can't justify the cycles for a repro, then we probably need to reprioritize this issue

**Comment by steeling** [comment]
So my theory on this bug is that UpdateStatus (which is called in a single place, and is triggered through regular proxy updates), will eventually reach a stable state, particularly if we enable a resync/ticker.

However there are other calls

1. https://github.com/openservicemesh/osm/blob/28b32389bb8d792d2ac2f8ab8433b647a4a0926d/pkg/ingress/gateway.go#L143
2. https://github.com/openservicemesh/osm/blob/8fd236e8e104279b4d951a32720e06f4257fd80a/pkg/k8s/announcement_handlers.go#L71 (part of issue #4845)

And we are adding more with the upcoming root cert rotation. I think this warrants a generic retry mechanism for API calls that are performed outside of a reconciliation loop.

But we need to be careful with race conditions in that a future write should cancel out previous writes. 

It's also possible that we never succeed. We should add metrics/traces for each call so users can provision alerts appropriately

**Comment by steeling** [comment]
will read the design doc and get to reviewing early next week

**Comment by keithmattix** [comment]
Some of the work around certificates will create another pattern for this
