### ISSUE TITLE
Event handling retains memory under moderate load

### ISSUE THREAD

**Issue by nojnhuh** [openservicemesh/osm#4623]
**Bug description**: When more than a moderate amount of Kubernetes events are processed by osm-controller, its memory usage continuously grows until it gets OOMKilled.

At ~10 events/sec, memory usage stays constant. At ~20 events/sec, memory usage grows. ~60 events/sec is enough to exhaust the 1G default memory limit in about 2.5 hours. 1k-1.5k events/sec hits the limit in about 3 minutes.

**Expected behavior**: osm-controller doesn't retain memory allocated for events that have already been processed.

**Steps to reproduce the bug (as precisely as possible)**:
(Using CLI/images built from 8bae12f7186d3bf7709951ba8c37e68e569f30c8)
```
osm install <image params> --set osm.deployPrometheus=true
osm namespace add default
for i in {1..20}; do k create service clusterip empty$i --clusterip=None; done
while true; do kubectl label ep --all --overwrite time=$(date +%s); done
# monitor memory usage in prometheus
```
The above will generate 1 event per second per service. Use `date +%s%N` instead of `date +%s` to relabel faster than once per second. Add more services or run more instances of the `kubectl label` loop to generate more events.

**How was OSM installed?**: CLI

**Anything else we need to know?**:
- Reducing from 20 events/sec to 10 events/sec stopped the memory usage from increasing, but it did not go down at all after ~1 hour. Reducing from 10 events/sec to 0 showed the same, where memory didn't continue to climb but also did not fall.
![image](https://user-images.githubusercontent.com/16093815/160913635-b27efec3-566e-435d-95b5-6e04dc7fb654.png)
- osm-controller memory heap profile for a different run right before getting OOMKilled: [oom-lots-of-events.pb.gz](https://github.com/openservicemesh/osm/files/8383123/oom-lots-of-events.pb.gz)
![oom-lots-of-events](https://user-images.githubusercontent.com/16093815/160914844-8364d6da-a25b-4180-b5e8-ab4a88b60746.gif)

**Bug report archive**:

**Environment**:
- OSM version (use `osm version`): 8bae12f7186d3bf7709951ba8c37e68e569f30c8
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.5", GitCommit:"c285e781331a3785a7f436042c65c5641ce8a9e9", GitTreeState:"clean", BuildDate:"2022-03-16T15:51:05Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.9", GitCommit:"56709e92afa973c26fad3d4a44723fefa51481b7", GitTreeState:"clean", BuildDate:"2022-03-10T07:59:33Z", GoVersion:"go1.16.12", Compiler:"gc", Platform:"linux/amd64"}
```
- Size of cluster (number of worker nodes in the cluster): AKS, 6 Standard DS2_v2 nodes
- Others:

**Comment by nojnhuh** [comment]
It looks like something in between the informers receiving notifications from Kubernetes and pulling that same event off OSM's broker's workqueue isn't keeping up with more than 10 events/sec.

If I modify the scenario above to run
```
while true; do kubectl annotate ep --all --overwrite date=$(date +%Y-%m-%dT%T%z); done
```

and log the values for those annotations with the following changes to osm-controller:
```diff
diff --git a/pkg/k8s/event_handlers.go b/pkg/k8s/event_handlers.go
index 8db16dad0..b368271ca 100644
--- a/pkg/k8s/event_handlers.go
+++ b/pkg/k8s/event_handlers.go
@@ -91,5 +91,9 @@ func logResourceEvent(parent zerolog.Logger, event announcements.Kind, obj inter
 	if o.GetNamespace() != "" {
 		name = o.GetNamespace() + "/" + name
 	}
-	log.Debug().Str("resource_name", name).Msg("received kubernetes resource event")
+	s := "received kubernetes resource event"
+	if o.GetAnnotations()["date"] != "" {
+		s += " from " + o.GetAnnotations()["date"]
+	}
+	log.Debug().Str("resource_name", name).Msg(s)
 }
diff --git a/pkg/messaging/broker.go b/pkg/messaging/broker.go
index f49c7d55f..abd0c1d0e 100644
--- a/pkg/messaging/broker.go
+++ b/pkg/messaging/broker.go
@@ -7,6 +7,7 @@ import (
 
 	"github.com/cskr/pubsub"
 	corev1 "k8s.io/api/core/v1"
+	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
 	"k8s.io/apimachinery/pkg/util/wait"
 	"k8s.io/client-go/util/workqueue"
 
@@ -199,7 +200,13 @@ func (b *Broker) runProxyUpdateDispatcher(stopCh <-chan struct{}) {
 // 2. Processes other internal control plane events
 // 3. Updates metrics associated with the event
 func (b *Broker) processEvent(msg events.PubSubMessage) {
-	log.Trace().Msgf("Processing msg kind: %s", msg.Kind)
+	s := string(msg.Kind)
+	if msg.NewObj != nil {
+		if o, ok := msg.NewObj.(metav1.Object); ok && o.GetAnnotations()["date"] != "" {
+			s += " from " + o.GetAnnotations()["date"]
+		}
+	}
+	log.Trace().Msgf("Processing msg kind: %s", s)
 	// Update proxies if applicable
 	if event := getProxyUpdateEvent(msg); event != nil {
 		log.Trace().Msgf("Msg kind %s will update proxies", msg.Kind)
```

I can see the informer logs keeping up but the broker logs falling behind:
```
{"level":"debug","component":"kube-controller","event":"endpoint-updated","resource_name":"default/empty6","time":"2022-04-06T20:42:30Z","file":"event_handlers.go:98","message":"received kubernetes resource event from 2022-04-06T20:42:30+0000"}
{"level":"trace","component":"message-broker","time":"2022-04-06T20:42:30Z","file":"broker.go:209","message":"Processing msg kind: endpoint-updated from 2022-04-06T20:38:14+0000"}
```

This shows that at 20:42:30, osm-controller is processing an event that happened at 20:38:14 after it had been running for less than 10 minutes.

```
{"level":"debug","component":"kube-controller","event":"endpoint-updated","resource_name":"events/empty9","time":"2022-04-06T20:52:02Z","file":"event_handlers.go:98","message":"received kubernetes resource event from 2022-04-06T20:52:02+0000"}
{"level":"trace","component":"message-broker","time":"2022-04-06T20:52:02Z","file":"broker.go:209","message":"Processing msg kind: endpoint-updated from 2022-04-06T20:43:00+0000"}
```

The time until osm-controller finally processes an event widens when the same load is maintained, here showing after almost 20 minutes the gap has grown to 9 minutes, all while the informer handler continues to process events in real-time.

I suspect like this ever-widening gap where kubernetes objects are being queued before being processed is the source of the memory leak. In #4568 when I was testing a metric to track the length of the broker's workqueue, that metric always showed 0 except right at startup in similar scenarios, which I suspect means the workqueue is not the ultimate source of the queued objects.

**Comment by shashankram** [comment]
@nojnhuh the workqueue is meant to rate limit k8s events so that the control plane does not get overwhelmed when there are too many events to digest. This is expected if you are seeing the same events being rate limited. This does not mean there is a memory leak, but if the workqueue keeps growing at a rapid rate, it will fill up and block reads till the rate limiter allows further requests, during which time the memory usage will increase. 
The default rate limiting enforced by the workqueue is 10 qps: https://github.com/kubernetes/client-go/blob/master/util/workqueue/default_rate_limiters.go#L37-L45

**Comment by nojnhuh** [comment]
@shashankram The [workqueue example](https://github.com/kubernetes/kubernetes/blob/8b5a19147530eaac9476b0ab82980b4088bbc1b2/staging/src/k8s.io/client-go/examples/workqueue/main.go) only rate limits re-enqueues due to failures, not every event from the informer handlers like we do, so it can keep up in real-time fine.

I suspect rate limiting every single event isn't worth it because putting that event on a queue seems like a relatively cheap operation. I would guess coalescing the events before broadcasting a proxy update is likely doing much more to keep the control plane from getting overwhelmed by the number of events.

Here's Prometheus with main:
![main](https://user-images.githubusercontent.com/16093815/162279147-a723148c-09b9-4f9c-9739-6f95158b4824.jpeg)

And here it is after only changing `AddRateLimited` to `Add` in the k8s informer handler:
![events](https://user-images.githubusercontent.com/16093815/162279280-a3791b57-1371-4150-9d10-0d3dc01b04b3.jpeg)

Overall I don't see any difference in CPU usage that rate limiting saves us.

**Comment by shashankram** [comment]
@nojnhuh I wasn't able to infer much from the graphs but would like to understand more about how this test was performed and what variables were used. Could you share more details regarding these (#num events, #memory usage, #cpu usage etc.) and compare with and without `AddRateLimited`? The basic idea of using `AddRateLimited` is to ensure we don't poll the workqueue in a tight loop. I don't think we should keep this unbounded, but we could increase the default QPS of the rate limiter to allow for more events. Practically, we want to avoid event storms which may arise in case of issues in the system.

I wouldn't change this just based on the workqueue example, since that's just an example to demonstrate how the workqueue works. However, if our testing shows that it performs poorly with the existing QPS even at moderate load, we should update the rate limiter instead of completely dropping it.

**Comment by nojnhuh** [comment]
This is the same scenario as I described above but scaled up:
- 100 services (and therefore endpoints) in a monitored namespace
- Spam updates on all the endpoints (I was running 20 replicas of a pod doing `while true; do kubectl annotate ep -n events --all --overwrite date=$(date +%Y-%m-%dT%T.%N) done`)

> The basic idea of using AddRateLimited is to ensure we don't poll the workqueue in a tight loop.

Did you measure what the cost of doing this is? From what I can see based on the graphs above the cost is negligible. AFAICT, `AddRateLimited` has been there since the workqueue was introduced so I can't track down any discussion as to why that needs to be rate limited and what the rate limit should be.

> Practically, we want to avoid event storms which may arise in case of issues in the system.

I would classify 1000+ events/sec as an "event storm" and it looks like with these changes we can handle that anyway without rate limiting at all. Is there a number you have in mind we need to be able to deal with?

Overall with these changes, memory usage stays constant over time, there's no noticeable difference in CPU usage, and events are processed in real-time.

**Comment by shashankram** [comment]
> This is the same scenario as I described above but scaled up:
> 
> * 100 services (and therefore endpoints) in a monitored namespace
> * Spam updates on all the endpoints (I was running 20 replicas of a pod doing `while true; do kubectl annotate ep -n events --all --overwrite date=$(date +%Y-%m-%dT%T.%N) done`)
> 
> > The basic idea of using AddRateLimited is to ensure we don't poll the workqueue in a tight loop.
> 
> Did you measure what the cost of doing this is? From what I can see based on the graphs above the cost is negligible. AFAICT, `AddRateLimited` has been there since the workqueue was introduced so I can't track down any discussion as to why that needs to be rate limited and what the rate limit should be.
> 

When the eventing framework was introduced to fix the various deadlocks in the code, the idea was to also avoid event storms in case k8s sends events at a rate the controller cannot handle. The default rate limiter was a good start for this. It doesn't make sense to come up with a random QPS without determining what an acceptable threshold is. This is the first time we are getting to profiling how the controller operates with various event QPS values.

> > Practically, we want to avoid event storms which may arise in case of issues in the system.
> 
> I would classify 1000+ events/sec as an "event storm" and it looks like with these changes we can handle that anyway without rate limiting at all. Is there a number you have in mind we need to be able to deal with?
> 
> Overall with these changes, memory usage stays constant over time, there's no noticeable difference in CPU usage, and events are processed in real-time.

If you classify 1000+ events/sec as a storm, then let's set that as the QPS for the rate limiter. The coalescing we have in the broker serves a different purpose - to not broadcast proxy events for every event received but to merge them if they arrive within the same window. The purpose of the rate limiter is to prevent the broker from continuously needing to process items from the queue. The dispatch functionality in the broker is not viewed as a rate limiter. If the implementation in the broker for the dispatcher (coalescing) were to change anytime, having the rate limiter do its job will avoid overwhelming the messaging layer. The point of a rate limiter is to ensure we don't execute unnecessary business logic in the broker in case of anomalies in the system (event storms).

**Comment by nojnhuh** [comment]
> the idea was to also avoid event storms in case k8s sends events at a rate the controller cannot handle.

What does it look like when the controller can't handle the events?

If it's a CPU spike, then from a profile I took with these changes it looks like over 50% of the CPU is being used just decoding JSON from the API (which happens before the informer handlers even run, so that's still true without these changes). The informer handler where we add to the queue takes less than 3% and `pkg/messaging.(*Broker).processEvent` takes less than 1%, so something else will be a CPU bottleneck before the workqueue.
[add.pb.gz](https://github.com/openservicemesh/osm/files/8447114/add.pb.gz)
[addratelimited.pb.gz](https://github.com/openservicemesh/osm/files/8447115/addratelimited.pb.gz)

If it's an out of memory issue, then we're already there even without these changes since rate limited events stick around until the rate limiter lets them through, which could be forever. Using `Add` will process events as soon as they come through so they never need to be kept around in memory while they're not on the queue.

> The coalescing we have in the broker serves a different purpose - to not broadcast proxy events for every event received but to merge them if they arrive within the same window.

I think this general approach of introducing more localized mechanisms to reduce load is better than having one very broad rate limiter when other components are capable of keeping up without it. If we find other components can't handle a certain level of load then I think we should do something similar to this there. Otherwise the whole control plane doesn't have the most accurate picture of what's actually going on in the cluster.

Overall I'm fairly confident the workqueue will never be a bottleneck given what we're queueing now so I think it makes sense to let this be unbounded.

**Comment by shashankram** [comment]
> I think this general approach of introducing more localized mechanisms to reduce load is better than having one very broad rate limiter when other components are capable of keeping up without it. If we find other components can't handle a certain level of load then I think we should do something similar to this there. Otherwise the whole control plane doesn't have the most accurate picture of what's actually going on in the cluster.

This is precisely why there is a rate limiting workqueue && coalescing of messages, and not just one or the other. Both serve different purposes. 

We currently do not have error paths implemented where we need to re-enqueue messages due to transient failure, but we definitely need to rate limit those to ensure we don't have the dispatcher executing in a tight loop with an unbounded amount of events. Have you tested this with a million events and seen the result?

**Comment by trstringer** [comment]
I do think we need to see what this looks like with a larger order of magnitude of events (million, etc.). Until we start to push this until we break something, both with rate limiting and without rate limiting, we will be unsure the behavior of the disaster with the different approaches.

I'm a little weary to drop rate limiting, but without much objective data behind my hesitation. Generally speaking I'm not a fan of blindly wasting cycles. But if it's an over-optimization then the breaking point tests should highlight that. If the CPU consumption is negligible then it's possibly a route we might want to take.

@nojnhuh, can you test this out both with and without rate limiting getting the metrics with a million events? It will be interesting to see what that looks like.

**Comment by shashankram** [comment]
One of the primary reasons a rate limiter helps is that it protects the controller from spending unnecessary cycles at all costs when the threshold exceeds reasonable limits. Even if the existing broker implementation is resilient to event storms at the moment, there is no guarantee it will in the future or when it misbehaves due to a bug. If we determine an acceptable threshold, e.g. 1000 qps, I would vote in favor of updating the rate limiter config vs completely bypassing it while processing events. It is hard to foresee scenarios like these in the wild, so I see little gain from not rate limiting events. I do agree that the default rate limiter config may not be ideal in many scenarios.

**Comment by steeling** [comment]
The multiple layers of rate-limiting is a little headspinning. Do we really want to process one event per second?

```go
func (b *Broker) runWorkqueueProcessor(stopCh <-chan struct{}) {
	// Start the goroutine workqueue to process kubernetes events
	// The continuous processing of items in the workqueue will run
	// until signalled to stop.
	// The 'wait.Until' helper is used here to ensure the processing
	// of items in the workqueue continues until signalled to stop, even
	// if 'processNextItems()' returns false.
	go wait.Until(
		func() {
			for b.processNextItem() {
			}
		},
		time.Second,
		stopCh,
	)
}
```

We're rate limiting what we're adding to the queue, *and* while reading from the queue, just to requeue it to a separate queue (pubsub), which has it's own capacity and therefore can block on it's own (ie: has a 3rd level of rate limiting), I think we can (hopefullly) agree its overcomplicated.

At the very least, I'd say let's remove the `go wait.Until` in favor of a blocking read on the channel. I'd also say let's err on the side of blocking on the read side not the write side (which will inevitably block if the channel gets full).

**Comment by steeling** [comment]
Looking at this a bit further:

1. Each pubsub has a capacity of 0, meaning writes to each subscriber will block.
2. There are a finite set of subscribers. We can assume they are running continuously, and constantly. Even with this (worst case scenario), I have 0 fear of overload
3. The workerqueue looks to have been implemented on the first implementation of the pubsub broker system, which makes me skeptical of its usefulness. At the very least, it looks like things have changed and it may no longer be serving its purpose. 
4. The current memory pressure Jon sees is bad. We should fix that.
5. We could actually get *improved* CPU performance (by removing some of the sleeps/context switches that are in the current system).
6. 5. Not processing a k8s event for 20 minutes is bad. We should fix that.
7. That last one is actually really bad. Consider a cascading failure scenario where a lot of things happen in k8s, triggering lots of events. A user's traffic policies get in a bad place. Now they go to fix it, but it could take OSM 20+ minutes to even process these events*


I say we take out the entire workqueue system and use the pubsub methods directly.

These types of edge case scenarios tend to become real world scenarios during failures.

**Comment by shashankram** [comment]
> The multiple layers of rate-limiting is a little headspinning. Do we really want to process one event per second?
> 
> ```go
> func (b *Broker) runWorkqueueProcessor(stopCh <-chan struct{}) {
> 	// Start the goroutine workqueue to process kubernetes events
> 	// The continuous processing of items in the workqueue will run
> 	// until signalled to stop.
> 	// The 'wait.Until' helper is used here to ensure the processing
> 	// of items in the workqueue continues until signalled to stop, even
> 	// if 'processNextItems()' returns false.
> 	go wait.Until(
> 		func() {
> 			for b.processNextItem() {
> 			}
> 		},
> 		time.Second,
> 		stopCh,
> 	)
> }
> ```
> 

This doesn't process 1 item per second, it processes items from the queue as soon as it is available.

**Comment by shashankram** [comment]
> Looking at this a bit further:
> 
> 1. Each pubsub has a capacity of 0, meaning writes to each subscriber will block.
> 2. Pubsub still guarantees us that we are not processing multiple events in each subscriber simultaneously, so there is almost no concern of overload here.
> 3. The workerqueue looks to have been implemented on the first implementation of the pubsub broker system, which makes me skeptical of its usefulness. At the very least, it looks like things have changed and it may no longer be serving its purpose.
> 4. The current memory pressure Jon sees is bad. We should fix that.
> 5. We could actually get _improved_ CPU performance (by removing some of the sleeps/context switches that are in the current system).
> 6. 5. Not processing a k8s event for 20 minutes is bad. We should fix that.
> 7. That last one is actually really bad. Consider a cascading failure scenario where a lot of things happen in k8s, triggering lots of events. A user's traffic policies get in a bad place. Now they go to fix it, but it could take OSM 20+ minutes to even process these events*
> 
> I say we take out the entire workqueue system and use the pubsub methods directly.
> 
> These types of edge case scenarios tend to become real world scenarios during failures.

I disagree with some of the comments made.
 
We need a workqueue for the following reasons:
1. To asynchronously process k8s events and not block informer goroutines on work the controller is doing. This is a standard communication pattern in controllers. Previously we had a simple PubSub without a workqueue, and the results were disastrous with deadlocks and blocking all over the code, see https://github.com/openservicemesh/osm/issues/4167.
2. Currently the controller doesn't handle error paths where an event trigger results in an error, and may need to be requeued for the system to reach its desired state. For e.g., if for some reason a `send()` fails on the XDS gRPC connection, Envoy will not reach its desired state without a retrigger. The workqueue helps in such scenarios with capability to rate limit how a controller can handle retries without being overwhelmed.

We definitely need to address the low QPS used by default by the existing rate limiter, but it is still to be determined what the consequences will be from doing so for a very large event burst.

**Comment by steeling** [comment]
Responses inline below:

> This doesn't process 1 item per second, it processes items from the queue as soon as it is available.

It absolutely does. Checkout the implementation for `wait.Until`.

>To asynchronously process k8s events and not block informer goroutines on work the controller is doing. This is a standard communication pattern in controllers. Previously we had a simple PubSub without a workqueue, and the results were disastrous with deadlocks and blocking all over the code, see https://github.com/openservicemesh/osm/issues/4167.

If there's a deadlock, that's a bug. IMO Fixing it with delays is a hack, and we should fix the deadlock if it still exists. These delays cause blocks (only during the delays, and because the workqueue impl is backed by a slice, it has an unbounded capacity), so although it won't cause a full deadlock, it can lock up during the delay portion which is not good. Because of this, we could actually remove the waituntil, and remove the AddRateLimited, and just use Add, and we would have successfully removed the deadlock. We will still be rate limited downstream of the workqueue.

Although I'd still advocate we fix the deadlock.

> Currently the controller doesn't handle error paths where an event trigger results in an error, and may need to be requeued for the system to reach its desired state. For e.g., if for some reason a send() fails on the XDS gRPC connection, Envoy will not reach its desired state without a retrigger. The workqueue helps in such scenarios with capability to rate limit how a controller can handle retries without being overwhelmed.

Each of these goroutines can only process one event at a time. That is, it reads from the queue, sends the response to the proxy, *waits for the proxy response*, and then finally completes the iteration before pulling off another item from the queue. I see no possbility for artificial, upstream rate limiting alleviating these any pressure on the proxies.

Again, I'd argue rate limiting to hide the lack of retries is error prone, and a hack. Let's fix the problem not mask it (and according to my above points we're actually not masking it anyways).

I think this further highlights our need for a level-triggered reconciliation loop.

Also, the whole workqueue processor is a custom implementation so I don't see how that's standard

**Comment by shashankram** [comment]
> Responses inline below:
> 
> > This doesn't process 1 item per second, it processes items from the queue as soon as it is available.
> 
> It absolutely does. Checkout the implementation for `wait.Until`.

I don't think so.

```
	// Start the goroutine workqueue to process kubernetes events
	// The continuous processing of items in the workqueue will run
	// until signalled to stop.
	// The 'wait.Until' helper is used here to ensure the processing
	// of items in the workqueue continues until signalled to stop, even
	// if 'processNextItems()' returns false.
	go wait.Until(
		func() {
			for b.processNextItem() {
			}
		},
		time.Second,
		stopCh,
	)
```

The function executed by `wait.Until` runs invokes `processNextItem()` continuously as long as there is an item in the queue. `processNextItem` only returns false when the queue is shutdown, so the processing should happen continuously. If the queue shuts down for some reason, then `wait.Until` will try to reinitiate it every 1s unless the controller signals the processing to stop via the channel passed to `wait.Until`. Processing of items in the queue does not happen every 1s.

**Comment by steeling** [comment]
> > Responses inline below:
> > > This doesn't process 1 item per second, it processes items from the queue as soon as it is available.
> > 
> > 
> > It absolutely does. Checkout the implementation for `wait.Until`.
> 
> I don't think so.
> 
> ```
> 	// Start the goroutine workqueue to process kubernetes events
> 	// The continuous processing of items in the workqueue will run
> 	// until signalled to stop.
> 	// The 'wait.Until' helper is used here to ensure the processing
> 	// of items in the workqueue continues until signalled to stop, even
> 	// if 'processNextItems()' returns false.
> 	go wait.Until(
> 		func() {
> 			for b.processNextItem() {
> 			}
> 		},
> 		time.Second,
> 		stopCh,
> 	)
> ```
> 
> The function executed by `wait.Until` runs invokes `processNextItem()` continuously as long as there is an item in the queue. `processNextItem` only returns false when the queue is shutdown, so the processing should happen continuously. If the queue shuts down for some reason, then `wait.Until` will try to reinitiate it every 1s unless the controller signals the processing to stop via the channel passed to `wait.Until`. Processing of items in the queue does not happen every 1s.

This playground link @3s demonstrates the wait i'm describing https://go.dev/play/p/nPsYahtNa61

**Comment by shashankram** [comment]
> > > Responses inline below:
> > > > This doesn't process 1 item per second, it processes items from the queue as soon as it is available.
> > > 
> > > 
> > > It absolutely does. Checkout the implementation for `wait.Until`.
> > 
> > 
> > I don't think so.
> > ```
> > 	// Start the goroutine workqueue to process kubernetes events
> > 	// The continuous processing of items in the workqueue will run
> > 	// until signalled to stop.
> > 	// The 'wait.Until' helper is used here to ensure the processing
> > 	// of items in the workqueue continues until signalled to stop, even
> > 	// if 'processNextItems()' returns false.
> > 	go wait.Until(
> > 		func() {
> > 			for b.processNextItem() {
> > 			}
> > 		},
> > 		time.Second,
> > 		stopCh,
> > 	)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The function executed by `wait.Until` runs invokes `processNextItem()` continuously as long as there is an item in the queue. `processNextItem` only returns false when the queue is shutdown, so the processing should happen continuously. If the queue shuts down for some reason, then `wait.Until` will try to reinitiate it every 1s unless the controller signals the processing to stop via the channel passed to `wait.Until`. Processing of items in the queue does not happen every 1s.
> 
> Oh I see, I missed the for. You're correct here. FWIW that code path will never trigger, since we never call `b.queue.ShutDown()`

Correct, to see how the processing works, see https://go.dev/play/p/ucjniJb3Sbu
Items are processed from the queue instantly.

**Comment by steeling** [comment]
With that, my points above still stand, and I think we should go with Jon's recommendation of removing the delay.

**Comment by trstringer** [comment]
I disagree with some of the points highlighted here. By definition this is not a deadlock. A delay or any form of rate limiting would never solve a deadlock. So while this isn't a true deadlock, this is resource contention.

Rate limiting is a common approach to solving this problem that I don't think we have data to prove that it isn't effective.

> I'd argue rate limiting to hide the lack of retries is error prone, and a hack. Let's fix the problem not mask it

Retrying consistently and linearly can have its own set of problems, I don't see it as a hack. And the requirement for a backoff is not necessarily a "problem". Resources that can have contention will naturally have this behavior.

My vote remains the same. Let's push this to the breaking point and see what this looks like with and without rate limiting. But I wouldn't just throw out rate limiting without concrete evidence. Otherwise all we can do here is theorize, and we shouldn't make code changes based off of theory.

**Comment by steeling** [comment]
> I disagree with some of the points highlighted here. By definition this is not a deadlock. A delay or any form of rate limiting would never solve a deadlock. So while this isn't a true deadlock, this is resource contention.
> 
> Rate limiting is a common approach to solving this problem that I don't think we have data to prove that it isn't effective.
> 
> > I'd argue rate limiting to hide the lack of retries is error prone, and a hack. Let's fix the problem not mask it
> 
> Retrying consistently and linearly can have its own set of problems, I don't see it as a hack. And the requirement for a backoff is not necessarily a "problem". Resources that can have contention will naturally have this behavior.

To clarify, I meant retrying to hide the errors (which would require a retry), is the hack, not to prevent the need for retries. Subtle difference, but wanted to point it out. In the end I maintain my argument that there's no resource contention on the channel receivers, since those process one at a time.

But overall, data speaks, and I agree with your approach of testing both sides

**Comment by nojnhuh** [comment]
I ran an experiment for @trstringer to see if the allocated memory is ever freed after the workqueue is done processing all of the backed up events. tl;dr Prometheus shows the memory is still allocated several hours later without any more events coming through, but generating more events doesn't increase it either like it does at startup.

Here's a Prometheus screenshot showing osm-controller memory usage, how many events per second the workqueue is processing, and how many items have been seen but not yet processed by the workqueue:
![image](https://user-images.githubusercontent.com/16093815/163015354-56fc574b-4ee4-41cd-aede-dd412a7027d8.png)

- I stopped generating events when Prometheus showed osm-controller using ~920MB of memory.
- The workqueue finished processing the pending events about 7.5 hours later and Prometheus didn't indicate any memory being freed during that time or for 10 hours after no events were being generated.
- Generating 20 events/sec after that did not show memory usage increasing in Prometheus like it does at startup.
- I took memory heap profiles with 0, ~5000, ~12000, and ~50000 events pending and all showed similar memory usage
  - [no-queued-events.pb.gz](https://github.com/openservicemesh/osm/files/8475063/no-queued-events.pb.gz)
  - [5k-queued-events.pb.gz](https://github.com/openservicemesh/osm/files/8475067/5k-queued-events.pb.gz)
  - [12k-queued-events.pb.gz](https://github.com/openservicemesh/osm/files/8475072/12k-queued-events.pb.gz)
  - [50k-queued-events.pb.gz](https://github.com/openservicemesh/osm/files/8475074/50k-queued-events.pb.gz)


Overall, my impression is that osm-controller does catch up eventually and doesn't keep memory from old events forever, though I'm out of my depth here so that could be incorrect.

**Comment by trstringer** [comment]
Instead of completely removing the rate limiter, which is a safeguard for future changes or scenarios, why don't we just raise the rate limiter QPS? That should put us in a good spot with this problem while also keeping the safeguard in place, but with a much looser configuration.

**Comment by steeling** [comment]
>The basic idea of using AddRateLimited is to ensure we don't poll the workqueue in a tight loop.

We never poll in a tight loop. We only poll at max, once the last proxy has finished updating the last message sent. If we keep the rate limiting, I think we should try to explain its intent.

There's a couple other bugs/edge cases I've found when digging through this code, which I think further highlights the need to simplify. I'll submit a draft PR by end of day with the changes I think we should introduce, and we can discuss there

**Comment by steeling** [comment]
![Untitled drawing (4)](https://user-images.githubusercontent.com/2824417/163227923-a0e35072-908e-43e0-ba7b-09785497feb6.png)

Here's a brief synopsis of our queueing/eventing implementation. There's also the global ticker which happens periodically. I propose we do the following (which is slightly different from the above PR):

1. remove the rate limiter from informers.
2. remove any and all coalescing from the broker. The broker will operate in a tight loop.
3. Move all coalescing (via singleflight, with a key grouped to its proxy uuid) to each proxies process routine. This will also operate in a tight loop, but only add 1 job at a time (per proxy) at max to the workerpool. This removes head-of-line blocking on a per proxy basis, since each proxy will continuously pull from its pubsub. This is a big win IMO.
4. Keep the workerpool in place to limit the number of concurrent updates across all proxies.

With this implementation we:
1. Alleviate growth on both the workqueue and the informer ring buffer
2. alleviate pressure due to head of line blocking on the pubsub
3. better semantics on guaranteed 1 job per proxy on the workerpool
4. better coalescsing.
5. A lot of simplication and code deletion!

**Comment by shashankram** [comment]
I propose we do the following (which is slightly different from the above PR):
> 
> 1. remove the rate limiter from informers.
> 2. remove any and all coalescing from the broker. The broker will operate in a tight loop.
> 3. Move all coalescing (via singleflight, with a key grouped to its proxy uuid) to each proxies process routine. This will also operate in a tight loop, but only add 1 job at a time (per proxy) at max to the workerpool. This removes head-of-line blocking on a per proxy basis, since each proxy will continuously pull from its pubsub. This is a big win IMO.
> 4. Keep the workerpool in place to limit the number of concurrent updates across all proxies.
> 
> With this implementation we:
> 
> 1. Alleviate growth on both the workqueue and the informer ring buffer
> 2. alleviate pressure due to head of line blocking on the pubsub
> 3. better semantics on guaranteed 1 job per proxy on the workerpool
> 4. better coalescsing.
> 5. A lot of simplication and code deletion!

I am open to simplifying and addressing existing bottlenecks, although in a systematic approach. Here's my suggestion on how we should go about this:.

1. Ensure removing the rate limiting (using `Add` instead of `AddRateLimited`) on k8s events does not result in a cascade of failures internally. The rate limiter was added to apply backpressure. If we can reliably drop the rate limiting of informer events and defer optimizations in the XDS layer, that is a good first step. We must thoroughly test this in a scale environment with several magnitudes of events per sec.
3. Keep the existing coalescing implementation as is because it does its job. I don't think it makes sense to reimplement what is working reliably if it just needs to be moved elsewhere in the code. The existing coalescer coalesces all broadcasts, not per proxy events. This reduces the load on the controller. Events meant per proxy are not to be coalesced by the global coalescer. I don't see the need for a per proxy coalescer when we can benefit from coalescing broadcasts at their origin.
5. Drop any XDS state machine/workerpool optimization in favor of using the XDS snapshot cache, and optimizing for it instead.

Also ignore the Ticker - it's a hack that when enabled, will periodically broadcast events to proxies. It was added as a recovery mechanism to workaround bugs in older versions where events may deadlock. I don't see a need for it anymore given our eventing mechanism does not deadlock.
