### ISSUE TITLE
Inject `osm-init` as FIRST initContainer instead of last

### ISSUE THREAD

**Issue by jcr010910** [openservicemesh/osm#4654]
I'm deploying an application via helm.
It's simply two pods: An app pod with DB pod.
The app pod has one initcontainer which verifies that the database pod is ready to respond to DB queries.

When we deploy the application outside OSM, it works fine.
When we add the application namespace to OSM and reinstall it, it fails.

the current work around, is to remove the side car from the DB pod `openservicemesh.io/sidecar-injection":"disabled"`
and once the app pod completes the two initcontainers (DB check and osm-init) we remove the annotation.

Any better work around / solution?
or is there a way to inject `osm-init` in a way to be the **first** initcontainer to run instead of last one?

**Comment by trstringer** [comment]
Thank you for opening this issue, @jcr010910! We're going to take a further look into this.

**Comment by shalier** [comment]
@jcr010910 Could I get the following resources:

- error logs for `osm-controller` and `osm-injector`
- `osm-mesh-config` meshconfig
- related Services yaml
- related Deployments yaml

**Comment by jcr010910** [comment]
@shalier , please check this file contents:
[4654.zip](https://github.com/openservicemesh/osm/files/8508110/4654.zip)

**Comment by shalier** [comment]
@jcr010910 The order of the init-containers isn't the issue because either:
- the init-container fails if it starts first because it redirects the healthcheck to a non-existent sidecar
- Or, it starts after to perform the healthcheck but mTLS wouldn't be applied since the sidecar isn't up yet

You should bring the healthcheck into your application code. You'll need to be careful since kubernetes doesn't provide sequencing on the order containers start in, so the app could start before the sidecar is up. To protect against this, you can use a backoff-retry with a max limit on the healthcheck

**Comment by steeling** [comment]
A couple thoughts:

1. If you do remove the initcontainer, you may want to look into something like [envoy-preflight](https://github.com/monzo/envoy-preflight) to ensure the sidecar starts before the application container. 
2. You could keep everything as is, but use an [Ingress Backend](https://release-v0-11.docs.openservicemesh.io/docs/guides/traffic_management/ingress/#ingressbackend-api), which would allow your database to be healthchecked without mTLS. However this may expose your database in an undesirable way as well. Note that the docs here also describe an Ingress, but you don't need that to work with an Ingress Backend. An Ingress Backend can simply configure the sidecar to allow traffic from outside the mesh with certain rules applied and when specified criteria is met.

**Comment by shalier** [comment]
@jcr010910 closing this issue, please re-open if there are any further questions on your end
