### ISSUE TITLE
Question: Pkg for implementing 'osm namespace add' in golang

### ISSUE THREAD

**Issue by ruokun-niu** [openservicemesh/osm#4855]
Hi! I am currently working on a project that uses the OSM's TrafficSplit capabilities. I am wondering if it is possible for me to implement `osm namespace add <namespace>` in a golang file, instead of using the cli (Main goal is to achieve everything without installing cli)? I have looked into OSM's packages and I was unable to find a function/package that achieves this.

**Comment by shashankram** [comment]
Hey @ruokun-niu, `osm namespace add` adds the `openservicemesh.io/monitored-by=<mesh-name>` label and the `openservicemesh.io/sidecar-injection=enabled` annotation on the namespace, by default. It provides flags that override the default behavior.

Depending on your use case, you could simply do the same in your Go code using k8s API. Since most of the CLI code is defined under `cmd/cli`, to make this exportable, you could also consider moving the relevant code to `pkg/cli`.
